### ISSUE TITLE
[Proposal] OTP support for IRCv3 SASL

### ISSUE THREAD

**Issue by ShutterQuick** [ircv3/ircv3-specifications#102]
#### Incentive

Adding support for OTP-login to services packages as of now would have to involve logging in SASL-users and prevent them from executing commands until the user provides an OTP token.
It is ugly, as it leads to the user being logged in, and getting their account name set, despite not having completed authentication. RPL_LOGGEDIN and RPL_SASLSUCCESS would also be somewhat misleading.
#### Proposed solution

The simplest solution appears to me to be to tack OTP on top of what we already have.
When a SASL user with OTP enabled requests the mech-list, services would list its options prefixed with 'OTP-'. For example "OTP-PLAIN,OTP-EXTERNAL".
During authentication, the client would send its OTP token before doing the rest of the auth like normal. The OTP token should be verified after username and password.

Example with plain:

> C: AUTHENTICATE OTP-PLAIN
> S: AUTHENTICATE +
> C: AUTHENTICATE MTIzNDU2
> S: AUTHENTICATE +
> C: AUTHENTICATE c2h1dHRlcgBzaHV0dGVyAHlheXBvbmllcw==
> S: 900
> S: 903

Example with external:

> C: AUTHENTICATE OTP-EXTERNAL
> S: AUTHENTICATE +
> C: AUTHENTICATE MTIzNDU2
> S: AUTHENTICATE +
> C: AUTHENTICATE +
> S: 900
> S: 903

This should be fairly simple to implement in existing software, as it can handle authentication in the existing providers as normal after dealing with the OTP part.

**Comment by jwheare** [comment]
https://tools.ietf.org/html/rfc2444 exists and would probably work with the standard SASL mechanism. If anyone implements it we could add it to http://ircv3.net/docs/sasl-mechs.html
