### ISSUE TITLE
Deprecate and eventually phase out CAP CLEAR

### ISSUE THREAD

**Issue by Elizafox** [ircv3/ircv3-specifications#134]
Hello,

CAP CLEAR is of dubious utility to client authors and of very dubious utility to users. It is not desirable that features be able to be turned off (just do not request CAPs you do not want), and may in fact harm user experience by being in the spec - it just screams "don't push this button" to anyone who comes across reading it. It also is limited in utilty by sticky caps, which cannot be removed once requested.

The only use case that even came up in discussion in #ircv3 was for bouncers - but servers cannot even send CAP CLEAR, making it useless for even this purpose. A well-written bouncer should be able to translate caps, anyway, or mandate them if needs be.

Anecdotally, the only reason I can find that it's even in the spec was apparently because in the past, it was desirable to demonstrate that everything was optional and could be turned off at any time for political reasons. Such political reasons have long since passed, as CAP is now a thing of the present and implemented by most major clients - sans CAP CLEAR in any of them known to me :).

**Comment by kaniini** [comment]
:+1: i have yet to find any client which legitimately sends `CAP CLEAR`, and of course `/quote CAP CLEAR` is just begging for trouble.

**Comment by SaberUK** [comment]
:+1:

**Comment by kaniini** [comment]
Lets do this as an errata update against the 3.1 spec.  I'll submit a PR in a moment.

**Comment by janicez** [comment]
I'm going to posthumously oppose this motion, as what if something breaks in a non-sticky cap and the user has to turn all of them off to try a process of elimination? CAP CLEAR would save a few bytes.
