### ISSUE TITLE
[Suggestion] Session Info Saving

### ISSUE THREAD

**Issue by B00mX0r** [ircv3/ircv3-specifications#142]
Note that this is the first proposal I've thought of/made, and it's definitely a first draft.
# Session Info Saving (Needs Discussion)
## Purpose
To allow easy restoration of metadata from a previous session via a LOAD command activated by a capability. Sort of a combination of services and #101 
## What
The IRCd, upon a client with the data-save cap enabled executing a command immediately before /quit, will save specific user data to a file or memory (IRCd maintainer's choice). The exact data and/or metadata saved is configurable by the server owner, and clients can see which data is saved via the value sent from a CAP LS (more on this later). The data saved MUST be identifiable by the UID of the destroyed session and a special key given as an argument to the save command (a password of sorts). Any session who loads the data-save capability can then execute LOAD (UID of destroyed session) (key) to restore saved data. 
## CAP
CAP data-save=(time data will be saved in minutes);(data that will be saved);(metadata that will be saved)
Here's an example using data from InspIRCd's /check command:
```
CAP * LS :data-save=1440;nuh,realname,modes,snomasks,signon,nickts,lastmsg,opertype,modeperms,commandperms,permissions,connectclass;accountname,swhois
```
## Example
```
Client: CAP LS 302
Server: CAP A LS :data-save=1440;realname,signon;swhois
Client: CAP REQ :data-save
Server: CAP A ACK :data-save
Client: USER John john.net irc-server.net John
Client: NICK JOHN
Server: 001, 002, etc.
Client: SAVE foo
Server: (numeric) John :A foo
Client: QUIT
```
```
Client: CAP LS 302
Server: CAP B LS :data-save=1440;realname,signon;swhois
Client: CAP REQ :data-save
Server: CAP B ACK :data-save
Client: LOAD A foo
Server: (numeric2) B :Loaded A
Server: 451 LOAD :Not enough data saved. Please register.
Client: USER John john.net irc-server.net Steve
Client: NICK John
Server: 001
```
Note that in the USER command sent by B, all data was accepted like a normal registration except for the realname, which is John. B also has A's signon time and "swhois" if applicable.
## Justification
By allowing customization of data and metadata saved for every network and IRCd, network owners can take more control of their IRC network. Rather than defining a set of rules for what data-save can support in the value parameters, each IRCd can add support for their own variables, like InspIRCd's swhois. An IRC owner can choose to allow the support just for a couple of variables like signon time, while another owner may prefer to save user "vhosts" in case the services package on their IRC server isn't online when a user joins.
## Policy
For the most part, this capability defines a message structure, while it's up to IRCd maintainers to choose what "data" and "metadata" strings are recognized, and to communicate that information to server owners. Because each IRC daemon is different, has different variables, and has different features, it'd be last century to define variables which can be used for data-notify.
## Discussion Points
1. What numerics should be used? I've put (numeric) where a numeric should go.
2. What happens if a server owner wants metadata to be saved, but not data? If you're a bit confused on why these fields are separate, IRC daemons need to add support for every "data" bit they'll allow in data-notify, while metadata can be created and defined through external service daemons.
3. Should there be a maximum or minimum time for the time value in data-notify? A day? A week?
4. Could a user with malicious intent deplete server resources by spamming the save command? Whose responsibility is it to worry about this?
5. The freedom in what's specified in data-notify's CAP LS value can add more uniqueness to IRC daemons, but should a few keywords be established? For example, should we say that if your IRCd will allow saving a realname through data-notify, the title in CAP LS MUST be called realname.
6. Is this idea too plausible enough to gain the support of IRCd maintainers and client developers?
7. What's the best way for storing saved data?

**Comment by grawity** [comment]
At first glance, this seems unnecessarily complex, compared to storing this information based on the services account.

How do you distinguish between 'data' and 'metadata' here? Why is the opertype under "data" but account name under "metadata", if they both describe the connection in very similar ways?

If a client saves its security information (such as opertype or privileges), then gets killed (and possibly removed from opers.conf), can it still load the saved information afterwards and regain access? Similarly, if its services account is dropped?

(Also, even though this is only an example, I'm not sure if allowing the client to restore an old nickts is a good idea...)

What would the user interface look like? Should the client always request to save all, or specific, values?

**Comment by kaniini** [comment]
:-1: just implement proper roaming instead of all of this stuff which is just a convoluted alternative.  Proper roaming is quite possible and unlike this, is transparent to peer users and allows channel membership and statuses to be properly retained (until the roaming client pings out).  The typical usecase is recovery after a connection break, so really this provides nothing for that use case over proper roaming.

**Comment by SaberUK** [comment]
I agree with @kaniini on this. Allowing session resumption (#101) seems like it would be better.

**Comment by attilamolnar** [comment]
I agree with the previous commenters. This is old and no one has commented here to show support, so I'm closing this. If anyone thinks this should be implemented rather than roaming/session resumption, feel free to comment.
