### ISSUE TITLE
Site is down

### ISSUE THREAD

**Issue by techtonik** [ircv3/ircv3-specifications#153]
http://ircv3.org/ 

```
404

There isn't a GitHub Pages site here.
```

**Comment by SaberUK** [comment]
Try ircv3.net for now. We're waiting for whoever has access to the .net domain and commit access to change the CNAME file and redirect the temporary domain.

**Comment by techtonik** [comment]
Why not just change Github description to point to ircv3.net?

WHOIS for ircv3.net points to @DarthGandalf

**Comment by DanielOaks** [comment]
This has been resolved now, pending further discussion

**Comment by gsf** [comment]
Still getting a DNS lookup error at ircv3.org.

**Comment by Aerdan** [comment]
Use http://ircv3.net until further notice.

**Comment by SaberUK** [comment]
It seems like Google Public DNS is broken. It resolves fine with other nameservers.

**Comment by gsf** [comment]
Could the website URL at https://github.com/ircv3/ircv3-specifications be modified for the time being?

**Comment by techtonik** [comment]
No 404. Closing.
