### ISSUE TITLE
cap-notify-3.2 specifies a vendor-prefixed batch called "example.com/cap-value"

### ISSUE THREAD

**Issue by dequis** [ircv3/ircv3-specifications#167]
@attilamolnar 

>03:23 < dx> what's up with that "BATCH +cap example.com/cap-value" in http://ircv3.net/specs/extensions/cap-notify-3.2.html
>03:28 < Aerdan> sending both CAP commands as a single transaction.
>03:29 < dx> i mean the example.com/ vendor prefix specifically. seems like it's defining a new batch type and simultaneously making it unusable
>03:30 < Aerdan> ask attila.
>03:30 < dx> hm. i guess the only way to ask attila is through the issue tracker?
>03:31 < dx> he's alive there
>03:32 < DarthGandalf> That can be made a proper batch type, if useful
>03:32 < DarthGandalf> without prefix

**Comment by jwheare** [comment]
Discussion moved to #168
