### ISSUE TITLE
Suggestion: Gradually phase out hostmask and ident

### ISSUE THREAD

**Issue by wilhelmy** [ircv3/ircv3-specifications#172]
I've brought this up on the channel at some point. I'll open a ticket so that it might not get lost.

Hostmasks and idents are redundant, especially as part of JOIN, PART and QUIT messages.
Given that they're also variable and most networks apply cloaks to them, I think they can be moved into a client's WHOIS and could instead be optionally replaced by a session identifier (e.g. the client's UID).

At the moment, the only time they're really relevant is for banlists, and there we might want to be able to have different ban types as well - like extbans by the realname field or TLS client certificate fingerprint - perhaps with a rework of the condition system on bans, like an "`hostmask is *.foo AND realname is *bar*`".

Comments?

**Comment by SaberUK** [comment]
:-1: This would break a ton of things such as bans and access lists based on masks.

If you wanted you could write an implementation which never sends the hostname and ident in the message prefix though. This is valid according to RFC 1459.

**Comment by wilhelmy** [comment]
Which part of it would break access lists? I'm essentially proposing two changes in a single ticket (bad style, sorry): Phasing out that hostmask/ident is sent as part of all messages and adding logical operations to extbans. As long as we don't modify the existing format, it should be fine from a backwards compatibility standpoint?

**Comment by Heufneutje** [comment]
I don't really understand the rationale behind this. A lot of things rely on hostmask matching so I don't think they're redundant at all. I also see very little gain in removing them.

**Comment by wilhelmy** [comment]
They serve absolutely no purpose as part of JOIN, PART and QUIT messages as well as part of the PRIVMSG prefix.

**Comment by wilhelmy** [comment]
Moreover, with hostmask switching/cloaks assigned by services and session resurrection (#101 - should that ever happen), they would be variable.

**Comment by DanielOaks** [comment]
Hostmasks, particularly in `PRIVMSG`, can be really useful for bot access control and rate limiting as well. Because `WHOIS` is usually pretty limited in speed, it would make things very annoying for some client bots, since they'd need to send out lots more `WHOIS` requests.

**Comment by jwheare** [comment]
:-1: creates more work for clients. If you don't want to see them as a user, that's a decision a client/preference can make for display, but there's 0 real benefit to removing them from the protocol and plenty of down sides.

AND operators (via some syntax or other) for extbans would perhaps be minimally useful but not in any related to removing hostmasks.

**Comment by grawity** [comment]
> They serve absolutely no purpose as part of JOIN, PART and QUIT messages as well as part of the PRIVMSG prefix.

Mostly agreed, but not for JOIN. They should remain on JOIN to avoid the need for manual query. (We actually _extended_ JOIN.)

> they would be variable

CHGHOST

> creates more work for clients

Many clients already cache those anyway, don't they... (And they have to cache accounts now.)

**Comment by ilbelkyr** [comment]
There is the case of PRIVMSGs from users you share no channel with, too. Not having to query for ident/host is really helpful there. (In fact, one use for account-tag is to avoid this issue, except with accounts rather than hostnames.)

**Comment by ProgVal** [comment]
> There is the case of PRIVMSGs from users you share no channel with, too.

Including people who send PRIVMSGs to a channel without being in one.

**Comment by synandro** [comment]
Not all networks use cloaks/spoofs.  EFnet for example.  Removing some that basic that has existed for 20+ years, does not seem like a good idea.

**Comment by wilhelmy** [comment]
Almost everybody seems to agree that this is a bad idea.
