### ISSUE TITLE
Require SNI from TLS clients

### ISSUE THREAD

**Issue by attilamolnar** [ircv3/ircv3-specifications#176]
As discussed in #155, 3.3 clients should probably be required to support server name indication. Among other things, SNI enables servers to pick the correct certificate in case there are more than one.
It's also simple to implement: one line of code with most TLS libraries.

**Comment by Mikaela** [comment]
https://github.com/ircv3/ircv3-specifications/pull/155#issuecomment-140081841 is worth keeping in mind.
