### ISSUE TITLE
ctcp-s

### ISSUE THREAD

**Issue by SoniEx2** [ircv3/ircv3-specifications#179]
I want a `ctcp-s` tag with value `<version>` which is sent on channel join and /who. I also want a `CTCP-S <target> [version]` command. `CTCP-S <target>` queries CTCP-S support, `CTCP-S <target> .` disables it.

**Comment by SaberUK** [comment]
Strong :-1: from me on this. Use a vendor prefix for your toy features.

**Comment by dequis** [comment]
no. just no.

**Comment by SoniEx2** [comment]
I wanted to use metadata originally but I can't because nobody implements it and it doesn't show up on join.

**Comment by M2Ys4U** [comment]
:-1:

**Comment by Mikaela** [comment]
And have you opened an issue to clients that you would like to see them supporting metadata [linking to the spec](http://ircv3.net/specs/core/metadata-3.2.html)?
