### ISSUE TITLE
In-channel metadata

### ISSUE THREAD

**Issue by SoniEx2** [ircv3/ircv3-specifications#180]
There should be a way to set metadata in-channel, e.g. by using `user@#channel` as the target.

**Comment by attilamolnar** [comment]
Why?

**Comment by attilamolnar** [comment]
Closing as there is no good use case for this that cannot be implemented using channel metadata. Feel free to elaborate on what you had in mind and if there's interest I'll reopen because maybe there is a good use case that we don't see.

**Comment by ProgVal** [comment]
Actually, someone have been asking me to write a plugin for my bot that would do this.
No idea why, though.

**Comment by SoniEx2** [comment]
Use case was talked about on IRC. Includes temporary/volatile metadata such as current OP status (instead of using modes, it can use a channel metadata), which gets reset when the user leaves. (This is also easier to manage on the software side, instead of parsing and editing an "ops" key, which also has a length limit.)
