### ISSUE TITLE
intent=gzip;<potentially other intents>

### ISSUE THREAD

**Issue by SoniEx2** [ircv3/ircv3-specifications#181]
There should be an intent for gzip/DEFLATE-compressed message data.

Note: The syntax of `intent=gzip;<potentially more intents>` would be easily abused with `intent=gzip;gzip;gzip;gzip;gzip;...` and a zipbomb, and that's why I'm proposing "potentially *other* intents".

**Comment by SaberUK** [comment]
This is a terrible idea. :-1:

**Comment by SoniEx2** [comment]
Why? It'll allow slightly longer messages.

**Comment by dwfreed** [comment]
And how do you propose handling the case where the compression results in a carriage return, line feed, or null byte being part of the message?

**Comment by SoniEx2** [comment]
@dwfreed you could already send those using CTCP's low-level quoting

**Comment by dwfreed** [comment]
Which not a single client actually implements

**Comment by SaberUK** [comment]
We have been over this before in #ircv3 many times.

1. The server will have to understand CTCP and decompress the message if it wants to do spam filtering or any other kind of message manipulation.
2. Unpacking uncompressed data from a source you do not understand is a bad idea.
3. Truncating GZip data results in the message being impossible to decompress.
4. There are way better methods of allowing longer messages than using compression
   - Expanding the max line length.
   - Using a message continuation batch type.
   - Just splitting client-side and sending multiple messages.
5. Any value tagged with an intent should be able to be formatted by an unsupporting client as a normal message. A bunch of garbled data is not a normal message.
6. GZip isn't even a good compression algorithm anymore.

Etc etc

**Comment by SoniEx2** [comment]
> The server will have to understand CTCP and decompress the message if it wants to do spam filtering or any other kind of message manipulation.

We're talking about IRCv3 here, not CTCP?

> Any value tagged with an intent should be able to be formatted by an unsupporting client as a normal message. A bunch of garbled data is not a normal message.

The server can do the decompression.

**Comment by dwfreed** [comment]
> The server can do the decompression.

See the second point @SaberUK mentioned:

> Unpacking uncompressed data from a source you do not understand is a bad idea.

**Comment by SoniEx2** [comment]
Give me a 1000-byte gzip which unpacks to 1MB+ and I'll agree with you.

**Comment by M2Ys4U** [comment]
```dd if=/dev/zero bs=1000000 count=1 iflag=fullblock | gzip -9 | wc -c```
>1+0 records in
>1+0 records out
>1000000 bytes (1.0 MB) copied, 0.00610152 s, 164 MB/s
>1003

Close enough.

**Comment by dwfreed** [comment]
I get 1060 bytes for 1048576 bytes of zeros, also close enough

**Comment by aji** [comment]
> The server will have to understand and decompress the message if it wants to do spam filtering or any other kind of message manipulation.

It will have to understand and decompress it regardless to be able to send the message to clients who don't support gzipped messages.

**Comment by aji** [comment]
anyway :-1: this idea is underdeveloped and full of problems

**Comment by SoniEx2** [comment]
Underdeveloped? Maybe.

Full of problems? I don't think so. Care to list them?

**Comment by DarthGandalf** [comment]
You already got the list...

14.11.2015 20:13, Soni L. пишет:

**Comment by grawity** [comment]
This might be useful if IRC ever gets a binary-clean framing, but not in its current state.

(That said, has TLS or SSH ever actually had the problem of gzipbombs? Overall, compression seems better than continuations.)

**Comment by SoniEx2** [comment]
Oh, the binary issue... Didn't think of that...

Base254 would work.

**Comment by dequis** [comment]
>Overall, compression seems better than continuations

Continuations aren't great but they are going to be needed either way, if only for backwards compatibility.

>Base254 would work.

No. Your implementation idea used bignum libraries to expand that "base254". That's awful and not happening.

**Comment by SoniEx2** [comment]
Sorry I made a mistake. I meant base252.

**Comment by attilamolnar** [comment]
Please find developers who are interested in this. I'm closing the issue for now due to the lack of interest.
