### ISSUE TITLE
server-time with clock on wrong time

### ISSUE THREAD

**Issue by Mikaela** [ircv3/ircv3-specifications#182]
The spec doesn't say anything about what should be done when client has clock that isn't on correct time (if anything).

This issue was rised at ZNC (https://github.com/znc/znc/issues/1144) which git version attaches server-time to all messages and while there was discussion on #ircv3 (https://github.com/znc/znc/issues/1144#issuecomment-152802270) nothing was ever done to the spec.

Several solutions have been suggested:
* ZNC should revert https://github.com/znc/znc/commit/c17c8c022b7aa21bf2e689828b1fd0e46347c713 so only buffer playback (what happened when client was disconnected) has server-time.
    * Alternatively ZNC should add an option for disabling it (and there is no agreement on what is the best default).
* The user should fix their clock and ZNC has no issue.
* The user should use echo-message capable client.

If this issue is left alone, it will be encountered again as others (mainly IRCds) start supporting server-time too and it's better to resolve sooner than later (or too late).

**Comment by attilamolnar** [comment]
The user's wrong clock is the problem here, ZNC has no issue (your third point).

**Comment by Mikaela** [comment]
I believe the spec should still mention this case and move the responsibility to the user.

**Comment by attilamolnar** [comment]
It's up to the client to interpret the messages, if it sees a timestamp in the future it could warn the user or start ignoring timestamps from the server or maybe turn off the cap.

**Comment by Mikaela** [comment]
The spec doesn't tell that either even as a suggestion.

**Comment by SaberUK** [comment]
>I believe the spec should still mention this case and move the responsibility to the user.

Users don't read specifications. This is outside of the scope of IRCv3.

**Comment by Mikaela** [comment]
s/user/client/ if you prefer, but what I am after is clear statement that the server, whether it's bouncer or IRCd, is doing nothing wrong when it sends server-time and the client is on system with clock on wrong time.

I believe that the spec should at least mention @attilamolnar's second comment (https://github.com/ircv3/ircv3-specifications/issues/182#issuecomment-158758607).

**Comment by grawity** [comment]
Nothing new; mammon also sends time tags with every message (and @kaniini's testnet is still off by several minutes).

There was once a proposal for playbacks to be marked by a batch. I suggest that clients default to only accepting time tags within a playback batch, although it seems useful to optionally accept them always.

**Comment by Zarthus** [comment]
I can't get my clock functioning properly on Windows. Whenever it syncs it naturally lags behind a second or two. How would you suggest I "fix my clock"?

That said, isn't the idea of server-time that I start using server timestamps instead? How could it be that there is an offset in some timestamps and none in others? And if it is, why is my local clock involved with this at all - it's the server clock that is being used? Is my client using local timestamps for some messages? I'm not sure if I get this part.

**Comment by grawity** [comment]
> How could it be that there is an offset in some timestamps and none in others?

_Your own_ messages aren't echoed by the server¹; they're timestamped locally & by your own client.

---

¹ There might be a cap for that...

**Comment by Zarthus** [comment]
>Your own messages aren't echoed by the server¹; they're timestamped locally & by your own client.

I get that much, but it makes no sense to me when this happens (on ZNC+mIRC) with server side events like kicks.

Case in point (identifiable information stripped):
```
(16:05:59) * nick (~ident@host) was kicked from #channel by @ChannelOp (kick reason)
(16:05:58) * nick (~ident@host) has joined #channel
```

In this case, the user probably had kick-rejoin enabled - causing them to immediately rejoin. However, my client's timestamp indicates that he joined a second before the kick happened. The kick was not issued by me - how could this still happen?

**Comment by attilamolnar** [comment]
> Case in point (identifiable information stripped):
> (16:05:59) * nick (~ident@host) was kicked from #channel by @ChannelOp (kick reason)
> (16:05:58) * nick (~ident@host) has joined #channel

If the server sends timestamps in all messages then this example suggests broken behavior from the client as a KICK only happens when the server sends the KICK, not when the client sends the KICK to the server.

**Comment by kaniini** [comment]
> Nothing new; mammon also sends time tags with every message (and @kaniini's testnet is still off by several minutes).

Blame VMware... the damned thing won't keep in sync even with openntpd running.

> There was once a proposal for playbacks to be marked by a batch. I suggest that clients default to only accepting time tags within a playback batch, although it seems useful to optionally accept them always.

I disagree; the point of sending server-time with all messages is to make logs more easily authenticated.  With a master clock, it makes verification of IRC logs feasible -- if two trusted parties have the same logs, with the same clock time, then it is another data point that can assist with the authentication of the logs.

Instead, the `echo-message` capability should be recommended to resolve this issue as then the message will be sent back with a master clock timestamp; mammon does this already today.

(this ignores clock skew on the network itself, but that's out of the scope of this conversation, and there are many solutions to that problem already.)

**Comment by attilamolnar** [comment]
Is there anything to be done to the specs? If not I'd like to close this.

**Comment by Mikaela** [comment]
Yes, the specs should make echo-message requirement or document this case or make echo-message as base extension.

**Comment by attilamolnar** [comment]
I don't think the spec needs to be updated to elaborate on wrong system clocks, clients have plenty of ways to shoot themselves in the foot.

**Comment by Zarthus** [comment]
Not ircv3's concern as far as I'd say.

**Comment by Mikaela** [comment]
And what if clients decide to not implement server-time or believe that issues like https://github.com/znc/znc/issues/1144 are right and remove server-time?

**Comment by kaniini** [comment]
I don't think there is any evidence of that really.

**Comment by Mikaela** [comment]
How about https://github.com/znc/znc/issues/1144 where ZNC developer never replied until the last comment and closing it?

**Comment by kaniini** [comment]
That means the ZNC developer did not remove the feature, thusly who cares?

**Comment by jwheare** [comment]
Closing in favour of #199
