### ISSUE TITLE
RPL_ISUPPORT is used in the spec but not defined

### ISSUE THREAD

**Issue by ProgVal** [ircv3/ircv3-specifications#194]
The name RPL_ISUPPORT is used in [metadata](http://ircv3.net/specs/core/metadata-3.2.html#metadata-restrictions), [monitor](http://ircv3.net/specs/core/monitor-3.2.html#monitor-command), and in [userhost-in-names](http://ircv3.net/specs/extensions/userhost-in-names-3.2.html)

But it is not defined in RFC 1459 (nor in 2812).
The specification only tells it maps to 005 (in monitor's spec), but the syntax is never defined.

**Comment by DanielOaks** [comment]
The latest ISUPPORT draft seems to be
https://tools.ietf.org/html/draft-hardy-irc-isupport-00

I'm not sure we need to explicitly define it given its very widespread use
in software already. Maybe we could link to that page if we really wanted
to? (though I'm not sure linking to it would make that much sense)

**Comment by ProgVal** [comment]
I believe specifications must be standalone, ie. not rely on “widespread use” to be understable.
Linking to an immutable document such as this draft looks like a good solution.

**Comment by SaberUK** [comment]
The problem is that very few people actually follow the ISUPPORT draft. I don't think anyone implements escaping or negation (-TOKEN) for example.

**Comment by ProgVal** [comment]
How is that a problem?

**Comment by DarthGandalf** [comment]
Let's import that draft to IRCv3

2015-12-23 18:01 GMT+00:00 Valentin Lorentz <notifications@github.com>:

**Comment by SaberUK** [comment]
@ProgVal It seems a bit pointless to refer to a draft that almost nobody (if that) follows.

It would be nice to see ISUPPORT implemented properly though. Maybe we should add a cap for it?

**Comment by jwheare** [comment]
This is covered by #132
