### ISSUE TITLE
Case of intents

### ISSUE THREAD

**Issue by ProgVal** [ircv3/ircv3-specifications#196]
In my understanding of the current state of the spec, intents mapped to CTCP messages must have the same capitalization as the CTCP intent, i.e. upper case.

I think having them in lower case — or at least case insensitive — would be more consistent with other parts of the IRC protocol.

**Comment by SaberUK** [comment]
AFAIK unless a case map is specified the usual custom is to default to insensitive rfc1459 casemapping.

**Comment by jwheare** [comment]
Closing via #270
