### ISSUE TITLE
identify-msg

### ISSUE THREAD

**Issue by SoniEx2** [ircv3/ircv3-specifications#198]
identify-msg is a CAP which allows for client-side +R but I don't see it specified anywhere and inspircd doesn't support it, which means I can't deal with their +R not supporing /accept.

Basically, when a user sends a message, identify-msg adds a + or a - at the start of the message. + if the user was logged in when the message was sent, - if they weren't. The workaround of sending a /msg nickserv status on every private message (yes, someone did in fact tell me to do this) both wastes bandwidth and has a race condition.

Instead of doing it like in freenode, it could also be split into identify-chanmsg and identify-privmsg, reducing bandwidth usage, as the + or - wouldn't be appended to every single channel message.

**Comment by dwfreed** [comment]
Identify-msg is almost useless, because it doesn't tell you what account they're identified to.  Also, freenode's identify-msg will report - if you're not using a nick grouped to the account you're identified to.  This is better solved with account-tag.

**Comment by TingPing** [comment]
The combination of [account-notify](http://ircv3.net/specs/extensions/account-notify-3.1.html), [account-tag](http://ircv3.net/specs/extensions/account-tag-3.2.html) and [extended-join](http://ircv3.net/specs/extensions/extended-join-3.1.html) make identify-msg not needed.

**Comment by SoniEx2** [comment]
So I should request support for account-tag from inspircd?

**Comment by SoniEx2** [comment]
Has identify-msg ever been specified by IRCv3? If so, it seems wrong to obliterate the spec. Instead, it should be archived and clearly marked as deprecated.

**Comment by SaberUK** [comment]
>So I should request support for account-tag from inspircd?

No you shouldn't because we aren't interested in implementing it.

**Comment by SoniEx2** [comment]
@SaberUK then add an /accept for +R.
