### ISSUE TITLE
[meta] feature requests/suggestions should include functional mocks

### ISSUE THREAD

**Issue by kaniini** [ircv3/ircv3-specifications#213]
I have noticed a lot of change requests / feature requests are based solely in theory, which ultimately are not feasible to include for whatever reason.

This request is a procedural request to require specifications to include mocks so we (as well as observers/vendors/etc) can see the change in action, which should help with both improved specs as well as improved discussion.

Thanks.

**Comment by ChickenNuggers** [comment]
This could be implemented via a `CONTRIBUTING.md` file as users are actually notified before creating an issue.

**Comment by kaniini** [comment]
Sure, I dont know what language to use for that, and would rather defer to the people presently running the show.  I just think a mock requirement is helpful to demonstrate the process that went into making the spec.

**Comment by SaberUK** [comment]
:+1:

**Comment by SoniEx2** [comment]
:-1: Disallows IRC **users** to contribute to IRCv3. I think we should cater to users, not developers.

**Comment by kaniini** [comment]
@SoniEx2 with all due respect, that is the point.

**Comment by ChickenNuggers** [comment]
> Disallows IRC users to contribute to IRCv3. I think we should cater to users, not developers.

... No. The point is that users should not be able to request things at random.

**Comment by SoniEx2** [comment]
@ChickenNuggers They should be able to request what they want/need. If for some reason developers decide not to satisfy their request, the issue can be safely closed and optionally locked. That's how any properly-functioning issue/suggestion tracker should work.

**Comment by SaberUK** [comment]
I'm not sure I can imagine a use case where a user would be capable of suggesting a feature but not be capable of implementing it.

**Comment by ChickenNuggers** [comment]
If they want to request a feature, they can at least go on IRC and discuss it first before creating an issue.

**Comment by SoniEx2** [comment]
@ChickenNuggers I'd love to do that but I'm banned.

**Comment by ChickenNuggers** [comment]
@SoniEx2 And who's fault is that?

**Comment by SaberUK** [comment]
Lets not bring drama into issues.

**Comment by kaniini** [comment]
The IRCv3 specifications process is *not a free software project*.  While it has some characteristics that are similar, what we produce here are formal specifications meant for developers to use when implementing software.  Thusly, in my opinion, it is inappropriate for non-developers to participate here.

I agree that it is good to listen to IRC users to find out what they want, however, I do not think this is the appropriate mechanism for it.  If the IRCv3 organization wishes to engage end-users, it should be through an alternate process which allows for feasible concepts to be properly incubated by interested developers into specifications and then included through the standards process we use with present developers.  That process would include mocking out the spec, which would be compliant with #213.

**Comment by DanielOaks** [comment]
I feel like this could be good as a *should*, along with some other guidelines in a CONTRIBUTING.md file. Maybe something along the lines of:

*Your request should be specific, including either a detailed overview of the proposed feature with language specifics to be worked out, or preferably mocked-up raw IRC lines to show other members and observers of the working group the benefits of your proposed feature. If your proposal is sufficiently vague, it may be ignored or rejected by the IRCv3 Working Group on those grounds.*

**Comment by kaniini** [comment]
It should be stronger than that, proposed specs should be implemented somewhere so that people can play with them.  If we are taking requests from users, create a new mechanism for it.

**Comment by DanielOaks** [comment]
It's been brought up on IRC about creating a repository like `ircv3/ideas`, where people can submit feature requests that are not yet fully thought out (as in, have things like the actual raw IRC representation to be worked out) or are 'wishlist' items. Then, specifications (with a mocked-up implementation, as in available to download or visit an address and play with behind a vendor tag) would be submitted here, which makes sure this repo contains more concrete specifications.

At least, I think it ended up somewhere around there.

I like how it sounds. I wonder whether it'd disadvantage those vendors whose projects aren't as well-suited for rapid turnaround of features. But it does make vendors think harder about the specs they throw towards the real repo, which is nice.

**Comment by SoniEx2** [comment]
@DanielOaks That does indeed sound nice! :+1:

**Comment by Mikaela** [comment]
> I'm not sure I can imagine a case where a user would be capable of suggesting a feature but not be capable of implementing it.

https://github.com/ircv3/ircv3-specifications/issues/103

> *Your request should be specific, including either a detailed overview of the proposed feature with language specifics to be worked out, or preferably mocked-up raw IRC lines to show other members and observers of the working group the benefits of your proposed feature. If your proposal is sufficiently vague, it may be ignored or rejected by the IRCv3 Working Group on those grounds.*

With these requirements I would never have opened https://github.com/ircv3/ircv3-specifications/issues/103.

However the idea came from @kaniini, but I don't know if anyone would have opened the issue or how long time it would have took if  Ididn't do it.

**Comment by DanielOaks** [comment]
Well, that's probably something that would've gone into `ircv3/ideas` or the like. That's why just implementing these restrictions without that other place for the less-stringently-specified ideas to go would be bad imo, because it would restrict us.

**Comment by attilamolnar** [comment]
@kaniini Can this be closed in favor of #215?
