### ISSUE TITLE
[meta] Require implementations of specs before they're ratified

### ISSUE THREAD

**Issue by DanielOaks** [ircv3/ircv3-specifications#214]
This is something that's been discussed several times, mostly in relation to issues that have been brought up with, ie, `METADATA` and such.

I think we should more explicitly require implementations of specifications before they get ratified as part of a real IRCv3 release. Specifically, require something like at least two servers, at least one client, one bouncer, etc (under a vendor tag until it actually gets ratified). Some number that ensures we get a real level of coverage over a specification and have the opportunity for multiple participants of the WG to take a real look at any possible implementation flaws or mis-specified parts of the spec.

This would improve the specifications that we put out, help ensure that issues of scale and such are properly thought out from multiple perspectives, and ensure that it has **some** real-world support before we go putting something out there.

Note, this means before we push the button that says 'Release IRCv3.3', not before they get merged into this repo. If we want to push the 'new release' button and a spec does not meet these requirements, it should get bumped up as Message Intents was.

**Comment by SaberUK** [comment]
:+1:

**Comment by ChickenNuggers** [comment]
:+1:

**Comment by jwheare** [comment]
:+1:

**Comment by SoniEx2** [comment]
:+1:

**Comment by highflyer77** [comment]
:+1: + :100:

**Comment by kaniini** [comment]
:+1:

**Comment by DarthGandalf** [comment]
Yes.
C++14 is a good analog of this.

**Comment by attilamolnar** [comment]
This is being documented in #215.
