### ISSUE TITLE
Formatting Extension

### ISSUE THREAD

**Issue by SoniEx2** [ircv3/ircv3-specifications#220]
`formatting` Extension
======================

The `formatting` extension adds a `formatting` tag, as a replacement for IRCII/mIRC formatting codes. The tag MAY be activated before the realname is sent (see rationale). This tag has the following syntax:

    @formatting=pos-FG,BGflags/pos-flagsFG,BG/...

The next `pos` MUST be greater than or equal to the previous `pos`. 0 is a valid pos, and indicates the start of the non-tag part of the message.

`FG` and `BG` are numbers between 0 and 99, or a RGB color in `#RRGGBB` format. `FG` and `BG` may be omitted entirely. The comma is optional when specifying `FG` only.

When specifying no color change, `FG`, `BG` and the comma MUST be omitted. Not specifying either side of the comma behaves as if `99` was specified. (In turn, this means specifying only the comma resets colors.)

In the 0-99 format, the color must be at most 2 digits in length. `00` to `09` are valid aliases for `0` to `9`.

Values 0-15 and 99 in the 0-99 format are specified as follows:

| Index | Color |
|----|--------|
| 0 | White |
| 1 | Black |
| 2 | Blue |
| 3 | Green |
| 4 | Light Red |
| 5 | Brown |
| 6 | Purple |
| 7 | Orange |
| 8 | Yellow |
| 9 | Light Green |
| 10 | Cyan |
| 11 | Light Cyan |
| 12 | Light Blue |
| 13 | Pink |
| 14 | Grey |
| 15 |  Light Grey |
| 99 | Default/Reset Color |

The actual colors used are implementation defined. All other values are implementation-defined.

Flags
-----

There are 4 flags that may be specified:

| Flag | Action |
|---|------|
| b | Toggle **bold** on/off |
| i | Toggle *italic* on/off |
| u | Toggle <u>underline</u> on/off |
| r | Reset all formatting |

`r` may be specified at the same time as other formatting. In which case, all other formatting is ignored, but MUST be transmitted unmodified.

Legacy Translation
------------------
The IRC server MAY translate formatting to legacy encoding and MAY translate vice-versa as well.

Examples
--------

    @formatting=24-4 :user PRIVMSG #example :This message is in red!
    @formatting=28-4/31-,/38-4u/41-,u :user PRIVMSG #example :The red is in red! (with the second red underlined)
    @formatting=24-11,58/24-27,76/24-71,76/24-8,75/24-13,13/24-, :user PRIVMSG #example :This message is NOT colored but you can use the raw logs to retrieve the hidden message.

The latter contains `Help me!` encoded using 0-99 color codes, with 13 bits per specified formatting.

For a user without support for the tag, the messages would look like:

    :user PRIVMSG #example :\x034This message is in red!
    :user PRIVMSG #example :The \x034red\x03 is in \x034\x1Fred\x03\x1F!
    :user PRIVMSG #example :\x0311,58\x0327,76\x0371,76\x038,75\x0313,13\x03This message is NOT colored but you can use the raw logs to retrieve the hidden message.

Rationale
---------

The `pos` field starts at the start of the message part because some IRC networks like to insert formatting codes in inappropriate places, such as hostname or nick. Steganography is allowed because KVIrc uses it in realnames, to signal various kinds of information, and it's also useful in normal messages.

Notes
-----

`#RRGGBB` is a little-known format and is not supported by all clients.

**Comment by ChickenNuggers** [comment]
A few questions:

 * What happens if a server doesn't support it?
 * What happens if a client doesn't?
 * Why should we use this instead of the old method?

**Comment by SoniEx2** [comment]
See also intents.

**Comment by ChickenNuggers** [comment]
There is no intents section

**Comment by SoniEx2** [comment]
Added "Legacy Translation" and legacy translation examples.

**Comment by clokep** [comment]
:-1: This seems awfully complicated and doesn't offer a reason for why it's better than the previous formatting schemes. (Which is not perfect, but not as insane as other IRC specs. :smile: )

**Comment by SoniEx2** [comment]
@clokep It'd allow usage of `\x03`, `\x0F`, `\x1D`, `\x1F`, `\x02` in messages. Just like intents allows usage of `\x01` in messages. Then we'd be left with only NUL, CR and LF being disallowed in messages. We'd also be able to expand formatting codes almost indefinitely (strikethrough, blink, hide, etc).

**Comment by dequis** [comment]
...is this just for the sake of that gzip hack?

**Comment by SoniEx2** [comment]
No.

**Comment by ChickenNuggers** [comment]
Can you give a reason you would use `\x03`, `\x0F`, `\x1D`, `\x1F`, or `\x02` in any message?

**Comment by SoniEx2** [comment]
Not really, idk what they would be useful for. They are specified on neither the IRC spec nor the IRCv3 spec, tho.

**Comment by ChickenNuggers** [comment]
So this is just so we have some random characters?

**Comment by SoniEx2** [comment]
This is just so we specify formatting one way or another. We could specify it as it currently exists but I don't see that getting approved.

**Comment by Aerdan** [comment]
In what way is this superior to inline formatting...?

**Comment by ChickenNuggers** [comment]
Charybdis at least has `+c` to block color modes so I know some people would certainly approve of it.

**Comment by SoniEx2** [comment]
It's not a hack, and it's standardized.

**Comment by ChickenNuggers** [comment]
Instead of proposing something new why not just standardize the current format?

https://imgs.xkcd.com/comics/standards.png

**Comment by SoniEx2** [comment]
As long as it's standardized, it doesn't matter.

**Comment by ChickenNuggers** [comment]
Then it would be appreciated if you could close this issue and create a PR with a spec for what is commonly accepted.

**Comment by SoniEx2** [comment]
No, I'd rather stick by my spec. It makes colors opt-in instead of opt-out. It's also easier to strip on the server.

**Comment by SoniEx2** [comment]
Don't forget some IRC clients replace `\x03` (and other "formatting codes") with boxes and/or other such characters, instead of parsing colors.

**Comment by DanielOaks** [comment]
imo this doesn't offer any upsides compared to standard inline formatting, and if implemented then servers will need to do translation back and forth for older and newer clients anyway. I don't think there's a reason for client authors to implement this over the sort of formatting already widespread today.

**Comment by SoniEx2** [comment]
> and if implemented then servers **will need to** do translation back and forth for older and newer clients anyway.

When did I say that?

**Comment by ChickenNuggers** [comment]
So what happens if someone sends `\x03` to a server that supports the new version, if they don't support it?

**Comment by SoniEx2** [comment]
Just goes through. As it should.

**Comment by ChickenNuggers** [comment]
So, you translate `\x03` like normal but you ALSO support the new version? What's the point of the new version?!?

**Comment by SoniEx2** [comment]
**What's the point of intents when we have CTCP?**
=
(Note: This spec proposes a transition period similar to intents.)

The goal here is to fix bots and IRC clients which don't want to support mIRC's hacky color and formatting system.

Most bots will fail if you start your message with a \x03. With my proposal they would work instead. I would be able to shove syntax-highlighted messages through repl bots, too, without having to hack them full of strippers.

I have a few times met users who see boxes followed by numbers instead of colors when you attempt to send colors to them. This spec would also solve that. For example go on #gaygeeks @ freenode and ask around. (What if instead of seeing "this text in red" in red, you saw "^C4this text is red"? Or worse what if someone sent a rainbow message and all you saw was a bunch of "^C" and numbers, with some text thrown around here and there?)

**Comment by Aerdan** [comment]
Then their clients are broken. Your proposal does not in any way fix the problem of lack of formatting support; all it actually does is hide the problem.

**Comment by DarthGandalf** [comment]
> what if someone sent a rainbow message and all you saw was a bunch of "^C" and numbers

Rainbow messages are supposed to be unreadable... So WAI.

**Comment by SoniEx2** [comment]
@Aerdan Are some trans women broken because they chose not to cut their dick off? Is something broken because the creators made the design choice of not implementing some non-standard feature?
