### ISSUE TITLE
[meta] Removing myself from IRCv3

### ISSUE THREAD

**Issue by SoniEx2** [ircv3/ircv3-specifications#223]
So apparently I can't use analogies about my own experiences in an attempt to get things I want. (In case you're wondering [this](https://github.com/ircv3/ircv3-specifications/issues/220#issuecomment-183088232) is about me.)

So I'm just gonna leave and hope future contributors look at the closed issues, and hope they make something better.

**Comment by attilamolnar** [comment]
Please don't spam our tracker.
