### ISSUE TITLE
Server sent ids

### ISSUE THREAD

**Issue by highflyer77** [ircv3/ircv3-specifications#227]
This would open up all kinds of possibilities of being able to reference a message by id #. 

It was discussed yesterday by: sagerdearia that: 

>  <sagerdearia>  Hi all. I have been noticing that LinkedIn has been gradually becoming similar to
>                 Facebook, including ability to like posts, and I thought I'd suggest that IRC v3 
>                 protocol should incorporate the ability to like privmsgs sent to channels and 
>                 users
- **a globally sequential id # , could make this a possibility.**

And just now a message by: @dequis on issue #226 

> I'd rather leave that up to the implementation. It just needs to be unique-ish. It could be a reference to a globally sequential id in a server side log database, for example
- **a globally sequential id # , could make this a possibility.**  

Finally I'd like to say that I can think of many uses for this and doing this could be useful for a lot of different kinds of implementations to make them a reality.

**Comment by dequis** [comment]
When I mentioned globally sequential ids that was just an example, and one that isn't very representative of what servers will want to do. It was just meant to contrast against the idea of requiring "a hash of the message+username+timestamp". The only requirement should be uniqueness.

Globally sequential ids are terrible for many reasons. Ensuring that a sequence is kept in order across a distributed system is painful and/or very annoying. Keeping server side logs in a centralized database is rare and often undesirable for privacy reasons among others. That's something I can only imagine non-traditional servers will attempt to do, and even then they'd probably prefer databases that don't provide sequential IDs

>sagerdearia

Uhm I thought we had agreed that sagerdearia was a fairly obvious troll. Well, "troll" isn't the best way to describe it as that was light hearted. Still, terrible way to start a ticket.

**Comment by Aerdan** [comment]
As long as the server can map it to an id, global uniqueness is not required; s2s is for servers to figure out, and they already have.

**Comment by grawity** [comment]
> Ensuring that a sequence is kept in order across a distributed system is painful and/or very annoying.

What if the requirement was just "unique"? Allocate the 'counter' the same way as connection UIDs then, with server prefix + per-server counter.

> Keeping server side logs in a centralized database is rare and often undesirable for privacy reasons among others

You don't need logs, just a counter. Stash it in `ircd.tune`.

**Comment by highflyer77** [comment]
@dequis 
>Keeping server side logs in a centralized database is rare
I didn't mean that servers should do that, but to only serialize the messages. The implementer could to the logging for what they were trying to accomplish.
@grawity 
You beat me to it, but yeah, that's along the lines of what I meant.

**Comment by dequis** [comment]
@grawity I was just adding context to my quotes. Anything that looks unique-ish to the clients is good enough. I think aerdan put it best in the previous ticket:

>The mechanics of the id tag should be implementation-defined, yes, as long as the client doesn't see any duplication

**Comment by highflyer77** [comment]
I also thought that this could be useful for "multi-line" #208 because if BATCH was used to implement it, the current specs. for BATCH doesn't specify any specific ordering (please correct me if I'm wrong).  
And  
This could also be used to simplify things on the client side for things like: "bookmarking" of logged messages of interest or code examples, or making a link for linking to a previous message id., etc.

**Comment by jwheare** [comment]
Putting this here for posterity:

Use cases: replyto, edit, fave, reaction, split-continuations, multi-line, shareable permalinks, quoting, "retweeting", attachments

**Comment by jwheare** [comment]
I've started work on this here https://github.com/jwheare/ircv3-specifications/blob/26a74d12ccd7539b6ecb2a60c93e807278839582/extensions/message-ids.md

I'll open a PR once that's a bit more fleshed out, with examples.

**Comment by jwheare** [comment]
Closing in favour of PR #285.
