### ISSUE TITLE
Governance

### ISSUE THREAD

**Issue by jwheare** [ircv3/ircv3-specifications#233]
After a channel ownership dispute over #ircv3 on freenode involving a violation of the [IRCv3 charter](http://ircv3.net/charter.html), I have been given control of the channel. I believe this has the support of the stakeholders, but it's now more important than ever to solidify the governance model for IRCv3, clarify the roles of the stakeholders, and further improve and cement the charter as our code of conduct.

With that in mind, I'd like to make the following proposals, all of which are open for discussion, including naming.

# Technical Board

Building on the discussion in #222, a technical board should be established. The board will consist of members who have contributed materially to the IRCv3 specifications, and who work on major software projects in the IRC community. They will be responsible for the technical direction of the specifications, and will work towards consensus while considering input from all contributors.

My initial suggestion for the board members is as follows:

@attilamolnar / Attila (InspIRCd)
@DanielOaks / dan- (mammon)
@DarthGandalf (ZNC)
@dequis / dx (bitlbee/irssi)
@grawity (unaffiliated)
@jwheare (IRCCloud)
@M2Ys4U (Kiwi IRC)
@TingPing (HexChat)
@zadr / NoOneButMe (Colloquy)

This hopefully represents a broad range of active vendors and specification authors. Nominations for new appointments will be considered and decided by the board.

This initial list is a subset of the current [stakeholders document](https://docs.google.com/spreadsheets/d/1lIhsF3zgCRQpvPtJmujVp5RfZqVL6OEg3fIlnwCrhjM/edit#gid=0), which I propose should be transitioned to an informal "members" list, hosted on the ircv3.net website, and the term "stakeholders" should only be used to refer to the Technical Board from now on.

# Community Council

Separately, a community council should be established, responsible for the "meta" direction of the IRCv3 working group. This will involve maintaining and enforcing a modified charter/code of conduct. This document will clearly set out group governance, provide guidelines for how members are expected to behave, and explain the consequences in case of violation. It will also set out a process for reporting abuse and for appealing moderation decisions. I'll open a separate issue for updating the charter pending initial discussion here.

In addition, the council will be responsible for establishing contributor guidelines, and an acceptance process for new ideas and specifications (see #215).

Community council duties will include: helping people successfully contribute to the project, moderating behaviour in the #ircv3 channel and issue trackers, responding to abuse concerns and resolving personal disputes.

My initial nominations for members of the council are:

@DanielOaks / dan- (mammon)
@grawity (unaffiliated)
@jwheare (IRCCloud)

This list is short at the moment, because I see community management as a particularly demanding responsibility, and I don't want to presume anyone is prepared to take it on. I'm particularly keen to hear input on this aspect of the proposal. The people in this list have agreed to IRC moderation duties, but I haven't shared this full proposal with anyone until now so it's pending their final approval.

# de facto Benevolent Dictator, For Now (dfBDFN)

As I have been given control of the IRC channel and ownership of the Github organisation, it's my ultimate responsibility to guide the establishment of these proposals, which I view as simply a formalisation and clarification of how the working group is already operating.

The traditional role of a BDFL (For Life) is to move things forward and make decisions in case of a deadlock. I'm confident the proposals I'm outlining here aren't contentious, and that we'll be able to resolve most issues through consensus in future. But I'm prepared to make decisions where that falls through, including returning proposals to the drawing board where necessary.

However, the role of a BDFN/BDFL in future is undefined. IRC isn't something that can be ruled dictatorially against the will of the community, but I feel it's important for someone to be able to move things forward when contentious issues crop up. Whether that should be me forever though, I doubt. Primarily because I have other responsibilities outside the group, and it's unclear how much time I'll have to devote to organisational issues here. That said, ideally it won't be a role that's needed very much at all. We'll see.

# Prior art and further reading

* The general structure of this proposal borrows heavily from the [Ubuntu governance document](https://community.ubuntu.com/community-structure/governance/) (but don't take that as an endorsement of the organisation in general)
* OSS Watch have a nice summary of [open source governance issues and models](http://oss-watch.ac.uk/resources/governancemodels)
* Some more good ideas on [open source governance at the Eclipse Foundation](http://osdelivers.blackducksoftware.com/2012/10/16/open-source-governance-the-eclipse-model/)

**Comment by jwheare** [comment]
As well as the followup issue to update the charter, I'll open a separate issue for the technical board to discuss a sensible specification roadmap, to replace the current 3.3 bucket list in the IRC topic.

**Comment by DanielOaks** [comment]
The team structures and goals sound pretty decent, I can't see any issues with either of them. I think the Technical Board, that more focused group would be good, especially as #215 gets more completely worked out.

So long as the whole 'ruling' part isn't overused and is used to push the WG forward for our benefit as a whole, I can see the role of dfBDFN being useful.

If people are happy with me being on the council, I'd be happy to take on that role.

**Comment by dequis** [comment]
This sounds good to me, except the "dfBDFN" acronym which sounds horrible.

It would be nice if we could include someone from weechat in the technical board, but they don't really participate a lot in the discussions. A shame since it's one of the most up to date client implementations, but completely understandable.

>So long as the whole 'ruling' part isn't overused and is used to push the WG forward for our benefit as a whole, I can see the role of dfBDFN being useful.

The way I see it, it's not too different to how the people with push access to this repo took some decisions to close issues that weren't going anywhere. Of course, like any other power, it's possible that this may be abused - but knowing jwheare, that's extremely unlikely.

>I think the Technical Board, that more focused group would be good, especially as #215 gets more completely worked out.

Did you eat a couple of verbs there? Not quite sure what you mean, focused == less people? Or that the proposal focuses it more, therefore it's good?

**Comment by DanielOaks** [comment]
I think I did eat some verbs there. I blame being tired.

I think it's good to have that smaller group that can represent their respective projects when talking about things like requiring 'stakeholder support' for new feature proposals in that new process. Need to convince one or more of those groups that your proposal is worth putting forward before it can be submitted here.

And of course, working towards the technical direction of the specs through things like the spec roadmaps, which I think could be really helpful for the WG.

**Comment by kaniini** [comment]
> Building on the discussion in #222, a technical board should be established. The board will consist of members who have contributed materially to the IRCv3 specifications, and who work on major software projects in the IRC community. They will be responsible for the technical direction of the specifications, and will work towards consensus while considering input from all contributors.

So nobody from charybdis that has actually implemented 3.2 tags support then?  Oh-kay then...

**Comment by zadr** [comment]
These proposals seem solid enough, and like others, I'm comfortable with @jwheare being BDFN du jour instead of de facto BDFN.

If others are okay with me being on the technical board, I'm happy to be there.

Since this is governance, one other tension I'd like to raise is that I'd like to see the charter's ground rules expanded to have a code of conduct in place. Something like [this one](http://contributor-covenant.org), to make it clear that that we have minimum standards and expectations of behavior for participation.

**Comment by SaberUK** [comment]
>Since this is governance, one other tension I'd like to raise is that I'd like to see the charter's ground rules expanded to have a code of conduct in place. Something like this one, to make it clear that that we have minimum standards and expectations of behavior for participation.

We already have such a thing in the "Ground Rules" section of the charter. It just needs to be properly enforced which the new governance should help greatly with.

**Comment by jwheare** [comment]
Yup, I do think it should be clarified along the lines of a code of conduct. I've been researching some good short ones that I feel align with our values and will go into more detail in the followup issue.

And yeah dfBDFN was pretty firmly tongue in cheek. We can choose another name once this is properly written down.

**Comment by DarthGandalf** [comment]
General comment: I don't like bureaucracy. But so be it, I guess...

**Comment by DarthGandalf** [comment]
What about channel ops?
There should be good coverage of various time zones for some op to be online. Is it the same list of people? If so, which of two? If not, who else?

**Comment by M2Ys4U** [comment]
A *tentative* +1 from me... although I've been away over the last few days and I'll need to speak to other Kiwi stakeholders before giving firm agreement.

**Comment by jwheare** [comment]
Closed in favour of ircv3/ircv3.github.io#71
