### ISSUE TITLE
Issues with netsplit tracking and BATCH

### ISSUE THREAD

**Issue by Elizafox** [ircv3/ircv3-specifications#253]
Hi,

As pointed out by Jilles Tjoelker, there's no way to know if a netjoin correlates with a netsplit if the server comes back via another server. Consider the following scenario:

1.  Client is on d.example.org. a.example.org is connected to b.example.org and c.example.org, and d.example.org. In this example, a.example.org is acting as a hub.
2.  a.example.org splits. Batch is sent like to client on d.example.org: `BATCH 123 +netsplit d.example.org a.example.org`
3.  The client doesn't see what's happening, but e.example.org is acting as a temporary hub.
4.  All the clients come back from b.example.org and c.example.org when e.example.org reconnects to d.example.org. However, all the client sees is `BATCH 234 +netjoin e.example.org d.example.org`. The client has no way to correlate what netsplit they came from (:-1:), and has to heuristically guess based on nicks, which could have changed; new clients could have come in, or some clients may have left also. 

My proposed fix is that during the netsplit and netjoin batch types, the name of the server the client is on will be returned with each client as a tag. That way, it can be lined up properly on netjoin (at the very least, you know what servers are returning on netjoin).

**Comment by aji** [comment]
when a nickname disappears and reappears from view, you can't assume nothing else has changed. what information do you expect to be reusable?

**Comment by Elizafox** [comment]
I expect the servers that are involved in the split at the very least to be reusable. Clients can be heuristically reused and correlated (if their hostmasks match).

**Comment by aji** [comment]
I think this proposal is adding more to the semantics of netsplits and netjoins than is already there, so it should be considered carefully. the netsplit/netjoin batch types were originally just to collect up a bunch of potentially unrelated QUITs and JOINs into something clients could understand as belonging to the same event. my 2&cent;

**Comment by attilamolnar** [comment]
> Nonetheless I suppose you're right and this is only useful for cleaning up the presentation of splits and joins.

Indeed. If you wish to change syntax and semantics please open a PR with the changes.
