### ISSUE TITLE
STS suggestions / improvements

### ISSUE THREAD

**Issue by kaniini** [ircv3/ircv3-specifications#256]
Two things:

1. The spec should use "non-TLS" in places where it uses "non-secure" right now, as the spec is specific to TLS upgrades.

2. Say you have two IRCds on a single IP + DNS name, production IRCd uses STS while development IRCd doesn't.  Now you cannot connect to development IRCd via plaintext.  It should probably be documented that STS imposes policy for the entire DNS name.

**Comment by jwheare** [comment]
1) While much of the implementation details will be TLS specific, I think the spec should be as agnostic about the specifics of the underlying transport as possible. 2) is addressed in #257
