### ISSUE TITLE
Draw from PSYC protocol

### ISSUE THREAD

**Issue by kxra** [ircv3/ircv3-specifications#262]
http://about.psyc.eu/

**Comment by SaberUK** [comment]
Can you be a bit more specific? What features does PSYC have that you want to see on IRC?

**Comment by DanielOaks** [comment]
Yeah I'm open to this or drawing from Slack, etc. However, doing it on a feature-by-feature basis lets us properly evaluate and look at each proposal on its own.

**Comment by attilamolnar** [comment]
Hello @kxra

I agree with the previous commenters, if there is a specific feature you have in mind then please open an issue about that. If not and your suggestion is that in general we should look at other protocols to get ideas from, then we already do that and there's no need to have an open issue about it.

**Comment by kxra** [comment]
they have a page on what they believe IRC lacks: http://about.psyc.eu/IRC

some features: 
http://about.psyc.eu/Telephony
http://secushare.org/pubsub
http://about.psyc.eu/Social_graph
http://about.psyc.eu/Trust#How_psyced_implements_this
http://about.psyc.eu/Presence
http://about.psyc.eu/Scalability
http://about.psyc.eu/Multicast
http://about.psyc.eu/Newsfeed
http://about.psyc.eu/Routing
