### ISSUE TITLE
Client-only tag registry

### ISSUE THREAD

**Issue by jwheare** [ircv3/ircv3-specifications#268]
#251 `message-tags-3.3` was merged. It would be good to have some client-only tags specified before it's ratified.

This could start with the `icon` example from that spec: a way to show inline favicons for specific messages, e.g. when linking to a website.

```
@+icon=https://example.com/favicon.png :url_bot!bot@example.com PRIVMSG #channel :Example.com: A News Story
```

---

PRs:

* [x] #288 Reply
* [x] #289 Reaction
* [ ] #302 Icons

**Comment by attilamolnar** [comment]
Another idea from a past IRC discussion is stickers over IRC where the message body is the URL and the tag contains the indicator that the body is a sticker. Incompatible clients will display the URL, compatible ones can fetch the image.

**Comment by jwheare** [comment]
A few other possibilities off the top of my head:

* geotagging
* formatting beyond mirc codes, e.g. strikethrough, rgb colours, fonts, syntax highlighting, etc
* reply tagging (#226)
* slack-style attachments https://api.slack.com/docs/message-attachments#attachment_structure

**Comment by attilamolnar** [comment]
Another candidate: #163 Send messages to users in the context of a specific channel (IRCX whisper)

**Comment by grawity** [comment]
Not sure if it's worth trying to design and register everything upfront. Just have a few common examples like `+icon=…` (privacy issues?), `+charset=utf-8` or `+type=text/markdown`.

Reply tagging might be worth a spec of its own, as well as most other @jwheare's suggestions.

**Comment by jwheare** [comment]
The idea is that *all* tags should be specs of their own, so that clients can handle them properly. Agreed we shouldn't try to design *everything* up front, but it would be good to have *some* concrete examples initially to help people understand use cases.

**Comment by LFP6** [comment]
Would message editing fall into this category? That has some wider implications, of course, namely being able to reference the old message (as in replies). Slack-style reactions might also be similar. I hesitate somewhat though as those are both modifying previous messages. Does that apply here, or is that out of scope?

**Comment by jwheare** [comment]
Sure. I can imagine a client showing a little "edited" link that expands to show diffs. Could be as simple as @+edited=<messageid> or @+reaction=<messageid> tags.

Specifying these properly should be done in a separate issue/PR. This issue is just to make sure we have a place to link to the specifications.

**Comment by nwf** [comment]
Don't forget #202's aborted introduction of a message sub-channel/topic/subject tag ala zephyr instances / XMPP topic tags!  `@+subj`?

**Comment by jwheare** [comment]
As we've started to post client tags to the website, i'm closing this issue. Ideas for more tags can be submitted as new issues on the ideas repo.
