### ISSUE TITLE
Undo intents

### ISSUE THREAD

**Issue by jwheare** [ircv3/ircv3-specifications#270]
This is a reference issue for:

* [x] Closing out/commenting on the issues in #247
* [x] Merge PR to remove the 3.3 spec #271 

As stated in #247:

> Intents mix up a lot of different issues, a CTCP replacement, presentational tags, etc. There may be good and bad ideas in all of these.
> 
> As far as I can tell, there has been little interest in implementing the current 3.3 draft spec, and the original author has reverse their opinion on them, so it's possible it should be reversed out. Please comment if this assumption is incorrect.

No discussion or meaningful case was put forward to keep intents, so I'm reversing it out, pending any further discussions about its usefulness.

CTCP works and is broadly implemented, it possibly needs to be more consistently specced, perhaps on http://modern.ircdocs.horse/ or in an eventual harmonised RFC.

Anything else that was planned to be built on top of intents (i.e. things that didn't exist in CTCP) can now be built with 3.3 client-only tags.

If you still feel intents are relevant, please discuss in the comments or on IRC. This decision can be reversed, but the current state of intents is underspecified and out of date (pre-dates 3.3 tags), and its presence on the specs page is misleading.

**Comment by dequis** [comment]
+1 for removing current intents spec, if only because it's outdated and misleading. Let's get that one out of the way and discuss new features later.

**Comment by jwheare** [comment]
Done.

**Comment by SaberUK** [comment]
@jwheare Still needs to be removed from the list on the website repo as well as updating the specs submodule.
