### ISSUE TITLE
Messages with images

### ISSUE THREAD

**Issue by alexandrujuncu** [ircv3/ircv3-specifications#273]
Hi
I took a quick look over the current issues and (surprisingly) haven't found an existing similar suggestion (hope I am not mistaken).

First, I like seeing that IRC is getting a version bump and that clients and servers are already using these features. But I am surprised that there wasn't a push for a modern feature: images (or multimedia).

All modern instant messengers from Yahoo Messenger to Allo give users the chance to send images in messages.  I am pretty sure IRC still doesn't allow that. And perhaps it should. 

A lot of clients try to do this (afair, Pidgin had this feature) by  one of two options:
1) encode the image in base64 or similar and send it as a text message
2) send an URL of the image located on an external server

There are pros and cons to both, issue with the first being bandwidth needed and need for an external component for the second.

But having this as part of the protocol would standardise this feature and make it compatible across servers and clients. 

And don't get me wrong, I like the fact that IRC is text based (even on Hangouts I rarely use image sending). But a lot of users would like this [citation needed]. However having the option is always a plus.

You can always add a mode on a channel to make it text-only to limit traffic to members. I remember the days when sending coloured texts on IRC channels was the coolest thing on some IRC servers :) And there was a mode allowing these messages.

So I am opening this up for debate. Best case this gets some traction. Worse case we get some documentation on why it can't be done.

Thanks!
 Alex

**Comment by itslukej** [comment]
http://lmgtfy.com/?q=image+hosting

**Comment by alexandrujuncu** [comment]
That is not the point. Anything from email to Yahoo Messenger to Hangouts can use links to 3rd party image hosting servers. However all of them implement a way of attaching images inside the messages by protocol.
Not looking for a workaround but a feature.

**Comment by DanielOaks** [comment]
Yeah this is something we've looked at for a while now. Other than one of those two options, I'm not sure there's much of another way to do this (however, the inlining is limited due to message sizes, so there'd need to be something else related to this).

I'm interested in exploring this, so long as it doesn't introduce vulns and that sort of silly stuff.

**Comment by justjanne** [comment]
The sanest solution, with backwards compatibility, would be introducing a protocol extension to allow clients to upload images directly to the IRcd, and tagging messages with images in them with an image tag and the URL, and just sending the plain URL to normal clients.

Introducing images in base64 over IRC would be not only in efficient, but also lead to tons of other issues.

**Comment by alexandrujuncu** [comment]
I would go for something embedde rather than relying on external services (keeps things clean). 
Indeed, message size if the enemy here. And I am not saying it would be easy.
What I am guessing would be needed is a way for creating streams over IRC. Think of an individual IRC message as an IP packet. If so, it would require something like a lite TCP (more of an FTP) to make sure that several messages are part of a single stream (representing an image, for example). It would require sequencing and acknowledgements at least.
Again, I am basing this on some Pidgin plugin that did something similar over any messenger protocol (including IRC).

**Comment by dequis** [comment]
>The sanest solution [...] upload images directly to the IRcd

Handling uploads in the ircd itself (going through the irc protocol tcp connection) is not necessarily the sanest solution (the rest of the idea seems ok). Most protocols nowadays do file/attachment uploads in an out-of-band way and just pass a reference to the file to the server that handles messaging.

So -1 from me for anything that involves in-band file transfers.

**Comment by DanielOaks** [comment]
Easiest solution right now is just to have similar behaviour to irccloud and if you drag an image onto your client, it uploads it to <imgur/etc> and provides the url in the message. Embedding the image into the message would be primarily limited because of message size (and how many messages you'd need to send to get stuff across). The sort of thing you're talking about there is roughly analogous to just DCC sending files imo, simplifing that or building a system based on that out more, but even that'd be complex to do for anything more than privmsgs.

Interesting idea but it'd take a while, and how well doing it inline it translates into IRC is questionable.

**Comment by alexandrujuncu** [comment]
@justjanne when you say extension that would upload the image to the ircd do you mean something that uploads it via some other protocol (like http, FTP, DCC) and then sends metadata?
Or extension as in another type of irc message type that would just talk to the server to send the information?

**Comment by justjanne** [comment]
@DanielOaks: my suggestion was two separate protocol extensions:

One to tag a link in a message as being an image to be displayed inline, a second one (which I doubt anyone except IrcCloud's ZNC gateway would implement) for uploading images directly.

**Comment by alexandrujuncu** [comment]
@DanielOaks  I might be out of touch with DCC since I have last used it but please correct me if I am wrong: DCC requires IP to IP connectivity (thus NAT breaks everything), right?

**Comment by justjanne** [comment]
I'd prefer an external upload, and just transmitting metadata via IRC, but if you insist on uploading the image via IRC, I'd at least hope we could let the download run via an external protocol.

**Comment by DanielOaks** [comment]
@justjanne In that case, I think there could be something there as a client tag to mark specific URLs as images (to help clients detect how to handle them wrt load-on-click and such). Uploading to the IRCd I'm initially skeptical on, would need to see like @jwheare's input on it and/or a spec to convince me probably.

@alexandrujuncu It can work behind NAT, but there are other issues around DCC these days. Regardless, I don't think that sort of a solution would be workable so probably best to not worry about it.

**Comment by alexandrujuncu** [comment]
Using an external protocol complicates stuff.. new ports to open (NAT/firewall issues) sync with another service/process supplying that protocol.
Plus it ruins the beauty of the IRC architecture where you just rely on the IRC servers to do message passing. Basically the IRC servers are like routers in the Internet. The issue is just how to send more than just datagrams (or another analogy: how to fragment if we exceed MTU :P). Sorry, I am a network guy :)

**Comment by justjanne** [comment]
@DanielOaks: Uploading to IRCd isn't something I think we'll ever see either, but it was something I suggested because the OP demanded a solution for fully in-band uploading.

And uploading to IRCd once is a lot better than transmitting the actual, full image, as hundreds of IRC messages.

**Comment by alexandrujuncu** [comment]
@justjanne Not demanding anything :) I would explore all options.
The one with the data as well as the metadata contained inside the IRC messages seems like a better approach to me.
Oh and when I say IRC messages, I don't necessary mean just normal /msg . It may be a separate new command.

**Comment by DanielOaks** [comment]
Yeah with how IRC currently is, doing it in-band as part of IRC messages isn't feasible because there'd be a whole lot of 'em to transmit simple messages. Cap to allow image uploading to some ircd-defined endpoint which returns a url, and separately a client-only tag to note URLs that are images, would be what I think's a reasonable way to approach this issue.

@alexandrujuncu the issue with doing it through IRC is that the only real way to convey this sort of data is to do it out-of-bound, either through an external connection (similar to DCC) or through an 'external' service (either hosted or pointed to by the IRCd, or just an external image host).

**Comment by alexandrujuncu** [comment]
@DanielOaks agree. 
However, that would require clients to implement the IRC protocol as well as a secondary protocol (HTTP, FTP ). 
Would DCC work from client1 to server and then sever to client2 (well, actually client2 would have to be also connecting to server with all the NAT thing). Sort of what STUN works on VoIP.

**Comment by DanielOaks** [comment]
Given the status of this, let's move it to https://github.com/ircv3/ircv3-ideas/issues/4 for some more directed discussion.

**Comment by attilamolnar** [comment]
Moved to ircv3/ircv3-ideas#4 per https://github.com/ircv3/ircv3-specifications/blob/master/CONTRIBUTING.md#ideas.
