### ISSUE TITLE
Rewrite draft/message-tags to be self-contained

### ISSUE THREAD

**Issue by jwheare** [ircv3/ircv3-specifications#297]
At the moment it depends on having already read the message-tags-3.2 spec. It should instead be rewritten as a superset, and the individual 3.2 tags can point to it instead as they're still valid in the new format.

We can then consider removing the 3.2 spec from the site, or prominently marking it as obsolete.

Also, remove 3.3 references, in line with #265.

Add some clarifying language to address #307.

This is a blocker for ratifying the draft.

**Comment by jwheare** [comment]
Should also add something about how tags replace the need for future specs to use CTCP.

**Comment by lp0** [comment]
Please define:
 * What clients should do when the server's tags are too long?
 * What clients should do if the server's response interleaves client and server tags, because the tag data limits are hard to apply in this scenario?

**Comment by jwheare** [comment]
> What clients should do when the server's tags are too long?

We could add something like:

`If a server sends a message with more tag data than the allowed limit, clients MUST ignore the message`

> What clients should do if the server's response interleaves client and server tags, because the tag data limits are hard to apply in this scenario?

Either clients don't need to care, or they can consume server tags up to the 510 limit or the first received +client tag, then continue consuming client tags up the 4094 limit.

**Comment by lp0** [comment]
> Clients MUST ignore the message
That would be ok. It's not nice but there's not much else that can be done. It's hard to define where the RFC1459 message is in the line when this happens.

We could potentially state that clients should find the `' '` (if it exists before the end of the overall line limit) and then parse the RFC1459 message (ignoring all the tags).

> Either clients don't need to care
This is my preferred option as it's simpler for clients than having to do lots of string size checking - they should just parse any tags up to the 4605 byte limit.

**Comment by jwheare** [comment]
The merged spec got done in #351 but might be some clarifications that got missed. Need to double check the points raised here.

**Comment by jwheare** [comment]
Further clarifications added in #373
