### ISSUE TITLE
When should client-only tags be sent?

### ISSUE THREAD

**Issue by elyscape** [ircv3/ircv3-specifications#307]
The [IRCv3.3 message tags spec][message-tags-3.3] adds support for client-only tags, which servers should send unmodified to clients, along with a capability `draft/message-tags-0.2`, which indicates that all tags should be sent to clients, even if the client hasn't specifically requested the relevant capability. My question is this: when should client-only tags be forwarded unmodified to clients? The spec appears to imply that it should be done always, but it would make more sense from a backwards-compatibility standpoint to only do this if `draft/message-tags-0.2` has been requested.

[message-tags-3.3]: http://ircv3.net/specs/core/message-tags-3.3.html

**Comment by jwheare** [comment]
It's implied in a couple of places that clients must indicate that they support receiving all tags by negotiating the capability. Some extra language can be added addressed to servers to re-emphasise this. We'll clarify this as part of #297.
