### ISSUE TITLE
link-security

### ISSUE THREAD

**Issue by syzop** [ircv3/ircv3-specifications#321]
This one too, I have no idea if you guys find this CAP useful or not. Right now we have this implemented as ```unrealircd.org/link-security```.
If others find it useful then we could make it an IRCv3 draft and once accepted I will of course rename the CAP accordingly. If not, no problem at all. I understand it only has a limited purpose.

The link-security capability allows a server to inform clients about the current state of SSL/TLS security of the network.

Syntax:
```unrealircd.org/link-security=<LEVEL>```

Example:
```unrealircd.org/link-security=2```

There are three levels:
**Level 0**: One or more servers linked insecurely (not using SSL/TLS)
**Level 1**: All servers are linked with SSL/TLS, but at least one of them is not verifying certificates (prone to MitM attack)
**Level 2**: All servers are linked with SSL/TLS and verifying certificates
Note: a server connecting to a server on the same machine (localhost) can be counted as level 2. This is common with services.

The levels indicate a network-wide level. In other words: the entire network is taken into account, not just the directly linked servers to the server advertising this CAP.

The purpose of all this is that clients can receive more information about the security of the IRC network.

One of the things this tries to address is that servers may currently not be linked securely, giving users a false sense of security if two users connected over SSL/TLS are having a conversation. The conversation would be leaked in plaintext if it travels server bounderies (in case of level 0) or may potentially be intercepted in case of an active MitM attack (in case of level 1).

This could be used by diagnostics tools or shown by clients somewhere in an *About this server* page, an icon or whatever.

See also: https://www.unrealircd.org/docs/Link_security

**Comment by jwheare** [comment]
Yup, a nice signal, but as in #320 this would make more sense in ISUPPORT instead of CAP. Also worth mentioning the obvious fact that this could obviously be faked by a server that wanted to appear more secure than it was as it's not possible for a client to verify it. But perhaps nice info for a server that you already trust.

**Comment by syzop** [comment]
Posted a message in #320 regarding usefulness of doing it in CAP. The same (faking) came up there as well. Won't cross-post here since I think it are (mostly) the same arguments :)

**Comment by syzop** [comment]
I don't think there is much interest from others on this. Which I can imagine making sense. Let's just close this and it will stay a vendor specific tag then. No need for this to keep lingering around.
