### ISSUE TITLE
CAP ACK

### ISSUE THREAD

**Issue by syzop** [ircv3/ircv3-specifications#323]
The [IRCv3.1 specification](http://ircv3.net/specs/core/capability-negotiation-3.1.html) documents **client to server** CAP ACK as:
> the client sends it to acknowledge capabilities which require client-side acknowledgement.

and:
> usage is when[..] some capability names have been preceded with the ack modifier. ACK in this case is used to fully enable or disable the capability. Clients MUST NOT issue an ACK subcommand for any capability not marked with the ack modifier in a server-generated ACK subcommand.

IRCv3.2 [adds the following](http://ircv3.net/specs/core/capability-negotiation-3.2.html):
> Deprecation of sticky (=) and ack-required (~) capability modifiers
Servers SHOULD NOT denote capabilities which are sticky with the = capability modifier. Instead, they should send a NAK to any request which would disable the sticky capability.
Capabilities MUST NOT require an ACK from the client to be activated.

So, CAP ACK from client to server will never be used, right?
Since we don't use sticky or ack-required capabilities (never understood the purpose, glad they are retired) I removed the client CAP ACK command in UnrealIRCd git altogether. I just wanted to double check if that's okay.

I guess I'm also touching a general point which is that the 3.2 CAP spec augments the 3.1 one... which in itself isn't even complete (or maybe that's just my impression). It should really be one complete CAP specification without having to read v1, v2, v3, whatever.

Also, I find it odd to mix client to server and server to client commands in the list the subcommands. Like the "ACK" which is used in both directions, the "NAK" which is used S2C only and "END" which is used C2S only. More logical would be to use only client point of view. With the possible server replies in each section, in a general section or in a server replies section. Presumably the first would be best, but that depends on how many "common replies" there are.

Ah well, basically 1 question/double-check and some feedback. Sorry for it all being in one ticket.

**Comment by grawity** [comment]
Yes, if you simply never advertise or allow any client-ack `~caps`, then there's no reason you would ever receive a CAP ACK.

Currently there are no client-ack caps in use anywhere (as far as I know), and I think it's safe to assume IRCv3 won't be adding any such caps in the future. Most clients do not support them either.

**Comment by jwheare** [comment]
> I guess I'm also touching a general point which is that the 3.2 CAP spec augments the 3.1 one... which in itself isn't even complete (or maybe that's just my impression). It should really be one complete CAP specification without having to read v1, v2, v3, whatever.

Agreed. I'd like to rewrite all such specs (cap, sasl, message-tags) in future to be self-contained, detailing the differences in versions inline.

**Comment by syzop** [comment]
Thanks for the quick replies. Appreciated :)

**Comment by DanielOaks** [comment]
Note, I've ripped this out (client ACKs) and combined these specs in #327
