### ISSUE TITLE
'Ratify' SNI

### ISSUE THREAD

**Issue by DanielOaks** [ircv3/ircv3-specifications#331]
SNI is just something that's useful to push for, especially when servers have multiple hostnames (possible with hostname changes, network merges and etc). I don't think there's anything to do with the spec, so can we just remove the `work-in-progress` tag and call it a day?

**Comment by jwheare** [comment]
I still feel weird about this, it's not a CAP, it's just a strong recommendation. Maybe would fit better in the /documentation namespace. Dunno how that fits in with #329 though. Happy for us to recommend it on the site, but it doesn't really seem to fit in core or extensions. Maybe a new /recommendations namespace?

**Comment by DanielOaks** [comment]
I was gonna agree, and probably throw it into another directory with that change. I'd agree with a `/recommendations` or `/best-practices` directory

**Comment by jwheare** [comment]
Cool. Personally I dislike the term "best practices", gets thrown around so much and is usually cover for ill-informed subjective or out-dated stuff.

**Comment by DarthGandalf** [comment]
+1 for best practices. The term applies here, even if some people apply the term incorrectly.
To make it not ill-informed subjective, it should provide clear reasons why this practice is so good.

**Comment by RyanSquared** [comment]
I have added to my TLS guidelines for my ircdocs/best-practices guidelines, a [section] detailing the importance of SNI. I will be talking with relevant parties about adoption of the best-practices repo under IRCv3.

---

For legal reasons, the contributions that I made to ircdocs/best-practices were made with as little informed information from the IRCv3 draft spec (simply, the fact that the specification existed, and the copyright owner of the specification) as possible, and the IRCv3 draft spec was only checked after the commit to ensure that the fundamental details between the two were kept. However, no changes were made to the ircdocs version of the file after review, as no changes were deemed necessary to be made. Any changes to the ircdocs version that take influence from the IRCv3 draft will be specifically mentioned, and any similarity between the two specifications are purely coincidental.

[section]: https://github.com/ircdocs/best-practices/commit/7127a84097727f3eb77e454e5740ae2b79f28909

**Comment by DanielOaks** [comment]
Note for later, in line with the document/folder-structure reshuffle in #329 this should live as something like  `/guidelines/sni.md`  or `/info/` or something similar. The folder name itself doesn't matter, but yeah it's not a feature in the traditional sense of what we normally have on the site.

**Comment by DanielOaks** [comment]
This now lives under a more appropriate folder, I'll throw in a PR to remove the 'wip' tag if we don't already have a pr that does so
