### ISSUE TITLE
Remove my identity from all IRCv3 specifications.

### ISSUE THREAD

**Issue by Aerdan** [ircv3/ircv3-specifications#337]
What the title says. I do not wish to be associated with this project in any form.

**Comment by wolfy1339** [comment]
Relevant extensions: 
* IRCv3.2 Monitor
* IRCv3.2 Metadata
* IRCv3.1 `extended-join`
* IRCv3.3 Message Tags

**Comment by grawity** [comment]
IMHO removing someone from the authors list requires a patch/pr from the author themself.

**Comment by jwheare** [comment]
@Aerdan the license on these specifications requires that the copyright notice remains intact. If you want to remove your name, you could transfer your copyrights on these documents to another party, and they will need to accept the transfer.

If you wish to transfer copyright to the IRCv3 working group as a whole you may do that instead.

Please reply to this thread with your decision, by editing this template to choose **one** recipient you would like to receive the rights for each spec. I've pre-filled the other copyright holders from the existing specifications where they exist.

```
I agree to assign all currently held copyrights for the
following documents to the listed recipients.

IRCv3.1 extended-join Extension
https://ircv3.net/specs/extensions/extended-join-3.1.html
Recipient:
* IRCv3 Working Group

IRCv3.2 Monitor
https://ircv3.net/specs/core/monitor-3.2.html
Recipient:
* Lee Hardy <lee@leeh.co.uk>
* William Pitcock <nenolod@dereferenced.org>
* IRCv3 Working Group

IRCv3.2 Metadata
https://ircv3.net/specs/core/metadata-3.2.html
Recipient:
* IRCv3 Working Group

IRCv3.3 Message Tags
https://ircv3.net/specs/core/message-tags-3.3.html
Recipient:
* James Wheare <james@irccloud.com>
* IRCv3 Working Group

Signed,
Kiyoshi Aman (Aerdan)
```

Your response will be treated as a binding digital signature.

**Comment by jwheare** [comment]
Closing for lack of response.
