### ISSUE TITLE
Conflict between cap-notify and CAP 3.2 specification

### ISSUE THREAD

**Issue by tilal6991** [ircv3/ircv3-specifications#338]
The CAP 3.2 specification specifies that values are not allowed with DEL commands (only with LS and NEW) but the cap-notify specification says it is allowed for both NEW and DEL.

I would prefer to go with the CAP 3.2 specification - to me it doesn't make sense to have DEL with values.

**Comment by jwheare** [comment]
Thanks for reporting this. It's already being addressed in #327
