### ISSUE TITLE
The old IRC doesn't work well with RTL languages as Hebrew and Arabic

### ISSUE THREAD

**Issue by Stamimail** [ircv3/ircv3-specifications#340]
needs to find a solution how to let LTR and RTL writing in the same session.

ABC...DEF........................................................................................
...........................................................................................אבג...דהו
GHI...זחט...JKL...יכל......................................................................
.............................................קרשת...PQR...עפצ...MNO...מנס

**Comment by SaberUK** [comment]
This is a client issue not a protocol issue. You should probably ask the author of your client to look into fixing this.

https://en.wikipedia.org/wiki/Right-to-left_mark
https://en.wikipedia.org/wiki/Left-to-right_mark

**Comment by DanielOaks** [comment]
Yeah this is a difficult one to solve. Let's close this here for now, and if we have more concrete improvement ideas to discuss, we can open a new issue over in the [ideas repo](https://github.com/ircv3/ircv3-ideas). Thanks for the issue anyways, much appreciated :)
