### ISSUE TITLE
TCP Fast Open

### ISSUE THREAD

**Issue by TaaviE** [ircv3/ircv3-specifications#354]
Would it be possible to at least mention somewhere in the standard that both clients and servers should if-possible (e.g. TCP stack allows) allow the use TCP Fast Open, this would help IRC to surpass other messaging protocols in terms of connection establishment speed (especially with most servers using TCP+TLS which is quite slow).

**Comment by TingPing** [comment]
I think this is quite meaningless to IRC usage. For web browsers it makes sense because they constantly open new TCP connections and the responsiveness really matters. Even in that case though Google for example still doesn't even enable fast open suggesting to me at least its probably not ready.

**Comment by TaaviE** [comment]
> Even in that case though Google for example still doesn't even enable fast open suggesting to me at least its probably not ready.

This is caused primarily by low adoption and TCP ossification (it's probably also one of the reasons Google wants QUIC). Given that most IRC users at the moment are more tech-oriented they're more likely using OSs that support TFO, which means that if IRC clients and server would support it we'd see much better adoption that we're seeing with public web servers.

**Comment by TingPing** [comment]
> This is caused primarily by low adoption and TCP ossification

I don't actually believe this. Android, ChromeOS, and the server market all support TFO. I suspect Google has more valid technical reasons or it is purely a political move for QUIC.

Anyway lets assume TFO is perfect in all implementations shipping in this fantasy. Still what does IRC gain? You open few TCP connections one time so the latency improvement is meaningless.

**Comment by SaberUK** [comment]
I'm failing to see how IRC can benefit from TCP Fast Open when TFO is specifically designed to speed up making multiple connections. IRC connections are generally long lasting so no major benefit can be gained from using TFO.

**Comment by Herringway** [comment]
as long as networks want to do things like identd lookups, dns lookups and proxy checks, there's not going to be much gained from this

**Comment by TaaviE** [comment]
> there's not going to be much gained from this

Assuming my QUIC suggestion does not result in any adoption/providing IRC over QUIC this suggestion would mean faster connection resumption (in addition to establishing) for both desktop and mobile clients, latter benefiting the most from really fast connection resumption making the use of bouncers less mandatory for those clients.

**Comment by mbax** [comment]
@TaaviE [commented](https://github.com/ircv3/ircv3-specifications/issues/354#issuecomment-453880941)
> Assuming my QUIC suggestion does not result in any adoption/providing IRC over QUIC this suggestion would mean faster connection resumption (in addition to establishing) for both desktop and mobile clients, latter benefiting the most from really fast connection resumption making the use of bouncers less mandatory for those clients.

How does QUIC or fast open impact a server's decision upon reconnection to re-query for identd/dns/proxies?

**Comment by TaaviE** [comment]
@mbax I edited my original comment btw. But the answer to your question is that it might not, but implementing TFO will at least not slow down the time it takes to (re)connect.

**Comment by DanielOaks** [comment]
I'm sure someone will look into a TCP FO implementation for IRC at some point. But given handshakes are really rare, and that the majority of latency in establishing connections lies elsewhere, it's not a super big priority. Always appreciate input though! (Note to self, this would fit much better for services that frontend the raw IRC proto with their own one much more accustomed to reconnecting like [possibly?] Quassel and such, in my IRC practices work I'll look at it there.)

**Comment by SISheogorath** [comment]
To be honest I don't see why it should be part of IRCv3 at all. It's just an implementation option. Clients do TCP fast open by default on a kernel level and servers just need to enable the socket option and may modify their kernel config to allow/support it.

So why put it into IRCv3 at all? There is no need to specify such a suggestion as standard document as it doesn't result in any change at the IRC protocol level.

**Comment by jwheare** [comment]
Thanks for the discussion, but yup this is out of scope and of limited use.
