### ISSUE TITLE
Clarify whether multi-line CAP replies applies to ACK/NAK/NEW

### ISSUE THREAD

**Issue by jesopo** [ircv3/ircv3-specifications#359]
Given the 3rd paragraph here https://github.com/ircv3/ircv3-specifications/blob/f06aa95a/core/capability-negotiation.md#the-cap-ack-subcommand

> If an ACK reply originating from the server is spread across multiple lines, a client MUST NOT change capabilities until the last ACK of the set is received. Equally, a server MUST NOT change the capabilities of the client until the last ACK of the set has been sent.

and this conversation https://github.com/ircv3/ircv3-specifications/pull/327#discussion_r156116778

It seems appropriate to discuss a clarification on whether multi-line functionality (as-per-spec for `CAP LS` and `CAP LIST`) apply to other `CAP` command replies too.

If it *does* apply to `CAP ACK`, it really should apply to `CAP NAK` and `CAP NEW` too.

**Comment by jwheare** [comment]
I'm not sure it's safe to suddenly change whether other subcommands can use the continuation functionality. If a server were to make that change, existing clients implemented to the previously valid spec would fail unexpectedly.

What is probably needed is some clear advice on how exactly to deal with long/potentially split REQ/ACKs.

Something like "clients should bear in mind the line length limit, the prefix in use by the server and how many CAPs they're requesting when sending a REQ. If needed, multiple REQs should be sent to avoid truncation in both sending and in receiving the NAK/ACK replies."

The concept of an "ACK spread across multiple lines" isn't really a thing fwict, most implementations will either truncate the REQ or the ACK if they would result in a line >512.

**Comment by jwheare** [comment]
Some other discussion of this from the past: https://github.com/ircv3/ircv3-specifications/pull/327#discussion_r156116778

**Comment by DanielOaks** [comment]
Yeah let's not change existing ACK/NAK/NEW replies. Advice along the lines of jw's suggestions makes sense as advice to client authors.

**Comment by dequis** [comment]
This removed part of the spec kind of helped avoid the need of sending multi-line ack by explicitly saying servers can truncate it and clients shouldn't expect it to be complete: https://github.com/ircv3/ircv3-specifications/commit/d81c6e1e81a96325eadc457cb3961cbe35231806

**Comment by DanielOaks** [comment]
fwiw I think a server truncating an ACK is doing something very wrong (partly why I removed that block of text). I know my client-side stuff treats only the contents of the received ACKs and NAKs from the server as canonical, so any truncation would result in really confusing stuff.

**Comment by jwheare** [comment]
@dx that part was only about NAK, a truncated ACK would be pretty broken.
