### ISSUE TITLE
Expected forward compat behaviour with CAP LS

### ISSUE THREAD

**Issue by jwheare** [ircv3/ircv3-specifications#368]
What should a client that supports CAP LS 302 do if we in future introduce CAP LS 303. Should it assume 3.2 or 3.1 style responses and cap-notify?

**Comment by DanielOaks** [comment]
Same as current behaviour, servers should keep track of the highest-supported cap version from the client and send responses consistent with that cap version. Client does `CAP LS`, they get back 3.1 responses. Client does `CAP LS 302`, they get back either 3.2 responses (inc cap-notify) or 3.1 responses depending on what the server supports. I dunno about other servers but if a client sends `CAP LS 303` on Ora, they'll get 3.2 responses and cap-notify (but should assume either a 3.3, 3.2, or a 3.1 response depending on server support.

Are there any servers that would break if a client did `CAP LS 303` / incorrectly fall back to 3.1 responses even if the server supports 3.2 fine?

**Comment by jwheare** [comment]
I suspect many implementations fallback to 3.1 as it stands. Maybe another way of doing this would be to make future LS versions be negotiated like this:

`CAP LS 302 303`

Kind of silly and hypothetical, but shrug. If people want to check and post current implementation behaviour that’d be grand.

**Comment by jwheare** [comment]
> Are there any servers that would break if a client did CAP LS 303 / incorrectly fall back to 3.1 responses even if the server supports 3.2 fine?
 
Yes, prattle :) will fix this pending discussion though.

**Comment by DanielOaks** [comment]
...Heh, turns out Oragono falls into that category as well (silly dev expectations not matching written code). Maybe we should make a clarification on the spec that the digit should be treated as a version number by the server and clients with greater version numbers should be treated like the highest-supported version instead? (tl;dr do what we expect up there)
