### ISSUE TITLE
Expected behaviour when querying CAP LS after negotiation.

### ISSUE THREAD

**Issue by jwheare** [ircv3/ircv3-specifications#369]
If a client negotiates CAP LS 302 during registration but then later sends a plain CAP LS, should the server downgrade them to 3.1 and stop sending cap notify?

I would say not, spec should probably forbid downgrades explicitly.

**Comment by DanielOaks** [comment]
Ora assumes you support 302 forever and never downgrades. Makes sense to assume that I think?
