### ISSUE TITLE
labeled-response: how far should we go for a 100% correct implementation?

### ISSUE THREAD

**Issue by syzop** [ircv3/ircv3-specifications#380]
For locally handled commands labeled-response is all quite doable. For remote commands it becomes a bit trickier.

Think of ```WHOIS Nick Nick```

In such a case I would delegate handling of such a request to the remote server (the server with "Nick" on it, in this case), have that server initiate the BATCH and the labeled responses. (Now how this goes over the wire is beyond of the spec and this discussion)

The problem is that the remote server may go away half-way through the BATCH. Think of a network issue.

My question is, how far should we go with these things. Can we just not worry about it? That would result in a BATCH that never ends.

Or am I supposed to keep a linked list of outstanding requests and cancel these BATCH'es when the server delinks.

How far should we go?

Similarly, but another case:
Some commands are asynchronous, like a server linking request (/CONNECT)...

Others commands don't have a clear beginning or end or are really hard to track like a /TRACE or in UnrealIRCd /TSCTL ALLTIME or similar IRCOp commands that may result in a response from all servers or a subset of servers.

What would be the best course of actions for those "difficult cases". Can I just do an empty BATCH response? I doubt UnrealIRCd will be the only software which has these special cases so I figured I'd post it here.

**Comment by jwheare** [comment]
In my opinion you can not worry about it for "async" or remote actions. labeled-response is primarily about making echo-message usable. The spec was written more broadly to allow for other interesting use cases that might be worthwhile in future with other commands, so as not to be artificially limiting, but a lot of it is largely safe to implement as a best effort.

So yes, you can use an empty batch response if you don't have anything concrete to respond with, or whatever we decide to change that to pending https://github.com/ircv3/ircv3-ideas/issues/37

**Comment by syzop** [comment]
Do you mean you wouldn't do labels in case of any remote actions, such as ```WHOIS Nick Nick```? That is quite a common command. I can see how that would disappoint client devs.

**Comment by jwheare** [comment]
I'd say you *can* not do it, if it's too hard for you, not that you shouldn't do try :)

**Comment by jwheare** [comment]
How does insp handle this @SaberUK?

**Comment by SaberUK** [comment]
We forward tags between servers so it should work fine. Its not something i've specifically tested though.

**Comment by syzop** [comment]
My opinion (only for what it's worth, of course):
1. I don't think labeled-response for remote commands should be fully optional. As mentioned, commands like ```WHOIS Nick Nick``` are common from clients.
2. Similarly, I don't think there should be a blanket opt-out for asynchronous commands. I agree on the difficult cases, but for example ```LIST``` (which is async on about every ircd due to flood controls) should really have labels IMHO.

After all, one of the purposes of the labeled-response is that if 2 devices share 1 IRC session then only the 1 issuing the command (WHOIS or LIST) should see the response. If you allow to do without labels for remote WHOIS and LIST then this lowers the quality quite a bit IMO.

Or maybe have the server indicate "levels" of conformance in CAP LS? If so, I would suggest to only do the remote/not-remote distinction. I don't know. Maybe not.

Food for thought, anyway.

**Comment by SaberUK** [comment]
I don't think theres really any need to differentiate? At the very worst clients will just fall back to their current behaviour.

**Comment by syzop** [comment]
Yeah, that's a valid point as well. So does this this mean you also think it should be optional to support remote requests?

**Comment by jwheare** [comment]
I don’t know whether it should be explicitly optional, but implementations will inevitably have some cases where their best efforts slip through the cracks.

I don’t really think labels fully solve some of the main reasons for having things like route_replies anyway, but that’s possibly a discussion for another time.

**Comment by DarthGandalf** [comment]
My main reason for pushing for labeled responses was to eventually remove route_replies. I don't think behavior should be any different whether it's local server replying or a remote server. The client doesn't need to care.

> The problem is that the remote server may go away half-way through the BATCH. Think of a network issue.

Perhaps close the batch if the server which was supposed to send the response disconnected?

**Comment by jwheare** [comment]
It's worth noting that for a bouncer, just because a response has a label, doesn't mean it should only be sent to the client that initiated it. A whois query should be, but echoed privmsgs and any state changes (mode, joins, nick change etc) will need to be sent to all connected clients. So you still need some form of route_replies or similar tracking to determine which commands go where.

**Comment by DarthGandalf** [comment]
Sure. I'm talking about responses which are sent to a single client. In the proposal, some whoises do get labeled responses, some do not. With such implementation of it, route_replies would need to be preserved anyway, as is, forever. And that destroys half of value of supporting labeled responses in first place.

**Comment by jwheare** [comment]
Well the proposal doesn’t say that, it was just me that said that it *could* happen, and I might be wrong.

I will say though, as a client and bouncer dev, I won’t ever be relying on labels for reply routing, it would just be more work for no real gain, and the non label method would still have to exist for clients and servers without support for labels.

**Comment by DarthGandalf** [comment]
> would still have to exist for clients and servers without support for labels.

Yeah, that's why I said "eventually" :) Depending on labelled-response adoption, it might never happen.

**Comment by SaberUK** [comment]
>So does this this mean you also think it should be optional to support remote requests?

I think implementers should be encouraged to try as hard as possible to get completeness but there's probably going to be some places where it fails or is too difficult for some implementers.

>And what are your thoughts on the first question (the BATCH being cut off mid flight)?

Considering that the IRCd has no way to predict when replies to a specific message will be received I don't think its really possible for a server to reliably include 100% of replies within the batch.

**Comment by syzop** [comment]
I would not consider any remote command such as ```WHOIS Nick Nick``` "some cases where best efforts slip". Those are major commands. Common commands. Things where this feature can shine. I think not implementing labeled-response in remote commands at all would be wrong. I'm also glad that it sounds like the implementations of labeled-response that exist so far are not this lax.

Similarly, and as mentioned before, it is an expectation of mine that client devs would find it a pity if server implementations would be so lax that they would not implement it for remote commands. But, to know that for sure, we would need comments from client devs that are really interested in this feature and have thought about how they could and would use the feature.

All that being said, and regardless of my humble opinion and expectations, if you really consider "partial/simple implementations" as acceptable then the document should clarify this. Perhaps you even consider "extremely partial/simple implementations" acceptable, where labeled-response only works for PRIVMSG and NOTICE with echo-message and would return empty batches (or no label/batch at all) for all other commands. If so, then that should be clarified as well.
Right now the document uses the ```MUST``` wording and clearly does not permit the behavior you described earlier in this discussion. Quoting the spec:
> For any message received from a client that includes this tag, the server MUST include the same tag and value in any response required from this message. Servers MUST include the tag in exactly one logical message.

So if you feel that way, it should be changed to a ```MAY``` (there and elsewhere in the document).

**Comment by jwheare** [comment]
> I would not consider any remote command such as WHOIS Nick Nick "some cases where best efforts slip".

I probably wouldn’t either, and people who’ve implemented it wouldn’t either. So this seems like a case where you do have something concrete to reply with, so you should label it. So no disagreement there.

My comments on server implementations should be taken with the understanding that I have only implemented single server ircds, and don’t personally have a need for labels beyond making echo-message usable. However, others have a broader interest so my comments don’t override the stricter language in the spec.

I think there will still be cases where some response are not feasible to label, but it’s not necessarily possible to enumerate them all up front. So there should perhaps be a warning to clients that this may be a possibility and they should react as they would on servers without this capability. This isn’t an excuse for servers to produce lax implementations though.

You initially raised the difficulty of tracking remote events. I took that to mean there was some feasibility issue. If you can’t produce a labeled response without breaking the laws of physics then of course that has to be acceptable. Accepting that isn’t a carte blanche for lax implementations but you then expressed disappointment about losing the very example you were concerned about implementing properly. So I’m honestly now not sure what would make you happy in this spec :)

**Comment by syzop** [comment]
@jwheare Ok, yeah my case was about a BATCH possibly never ending and at the end of my opening post some rare commands that are asynchronous / have no clear ending. Then you generalized it to not having to do it for any remote requests at all which surprised me a lot. But I now understand that was all a misunderstanding, misreading and/or misjudging the effort involved with coding it. Good, that means there is no difference in opinion there.
Your last few sentences I don't understand, but it's probably not important I guess.

Speaking of confusion, but this time on my part, I wrote "to know for sure, we would need comments from client devs that are really interested". It is only now that I see that I missed multiple comments from @DarthGandalf that were already made before I wrote that. Sorry about that. And thanks for the confirmation and support. It really matters to me what client devs think of this feature. After all, that is what we are coding it for. And it seems like we are on the same page with regards to the usefulness about routing etc.

**Comment by jwheare** [comment]
All good. Sorry for any over-generalisation and confusion on my part, and yes you can just ignore the last sentence.

So, for something actionable here: maybe all that's needed is some language that in some cases servers might not feasibly be able to label a response (with examples) and clients should be prepared for this situation.

**Comment by syzop** [comment]
So, concluding, the idea is to keep it as a ```MUST```, but then have a little warning or exemption somewhere that in some rare cases (or however you would describe them), certain *different* behavior may occur.

Examples of these cases (again, to be mentioned or not) would be asynchronous operations such as a /CONNECT and commands that may not have a clear ending (eg: servers sending something back or not, depending on a certain factor).

Perhaps before trying to come up with a phrase, decide what would be acceptable for such cases?:
- Send a batch with 0 commands, then after that the command output
- Attaching no label to the output
- ??

My first reaction: leave it up to the implementation, so allow both/any/..

**Comment by jwheare** [comment]
This is addressed in #385
