### ISSUE TITLE
Update clients page informations

### ISSUE THREAD

**Issue by westor7** [ircv3/ircv3-specifications#381]
Hello,

Recently AdiIRC added support for `sts` and `message-tags` in 3.4 version.

I think you should update the https://ircv3.net/software/clients.html website by updating these to `yes` 

More informations: https://adiirc.com/changelog.php

- Thanks!

**Comment by dgw** [comment]
You can update it yourself with a pull request to this file: https://github.com/ircv3/ircv3.github.io/blob/master/_data/sw_clients.yml
