### ISSUE TITLE
labeled-response: maximum size of label

### ISSUE THREAD

**Issue by syzop** [ircv3/ircv3-specifications#382]
Right now, there is no length limitation of the label tag specified in the labeled-response draft specification.

I think there should be a size limitation in the labeled-response specification, as a 4000 byte label would be ridiculous. In UnrealIRCd I am not going to allow a label of insane sizes. I don't think I have to explain why this would be a bad idea, but just a few words just in case: these result in huge amplifications of commands/responses (read: flood and security issues), not only between client and server but between servers as well, for no good reason.

What do you think? Do you agree there should be a size limit in the spec? If so, what should the limit be?

I don't think a label tag of more than 32 bytes is meaningful in terms of uniqueness (roughly 6*32=192 bits of randomness/uniqueness, assuming 6 bits per character with alphanumeric tags plus a few specials), but I can take a bit more if you want to, like 64 (roughly 384 bits of uniqueness).

**Comment by grawity** [comment]
I'd go for approximately 36 bytes, makes it easy to just stick an 128-bit textual UUID in there and not care about stripping the dashes out... but can't see the point in more than 40 bytes. (As I understand it, label tags are connection-scoped, not long-lived like message IDs, so 64 bytes seems like overkill.)

**Comment by SaberUK** [comment]
InspIRCds current implementation requires that a label is shorter than 40 characters.

**Comment by jwheare** [comment]
40 seems fine, it still *just* allows for {brace-and-dash} style uuids, but my future proofing instincts are bristling a bit. 64 is probably overkill but would make me less worried, and probably doesn't represent any flood/security risk.

**Comment by jesopo** [comment]
big :+1: from me on 64

**Comment by grawity** [comment]
No objection to allowing up to 64 as the safety limit, although I still think (well, hope) actually using such long IDs is always going to be overkill for this particular purpose. I only used hex UUIDs as a likely-to-be-common example, but if 128 bits isn't enough, then just switching to Base64 blobs would fit 240 bits in 40 characters – that's nearly the size of a sha256 hash.

**Comment by syzop** [comment]
Yup, I agree @ 64 safe upper limit, preferably use less. And I'm glad everyone agrees there should be a documented limit. Thanks! ;)

**Comment by DarthGandalf** [comment]
I was thinking about having bouncer append its own data to label it got from client before sending the message to server; but it would be harder to do with such limits in place. However, I fully understand the need for the limit, and with a chain of bouncers like this, the label size would be unbounded.
So, also +1 from me.

**Comment by jwheare** [comment]
This is addressed in #385
