### ISSUE TITLE
+draft/typing typing-active messge rate

### ISSUE THREAD

**Issue by ItsOnlyBinary** [ircv3/ircv3-specifications#384]
The current spec for +draft/typing seems quite spammy, having to send typing-active within a 6second time frame to keep the user marked as typing causes quite a message amplification.

spending 30seconds typing a message can result in 5 - 10 messages being sent before the actual message gets sent. On larger networks this can result in much more load/data on the server.

I suggest that everything gets much more relaxed, tagmsg are only sent when a change in state has occurred and more assumptions are made on the client side.

I have had a go at rewriting the format section of the spec as i think it should behave, hopefully changes can be made to head in this direction.

> Format
>
> A typing notification is represented by a TAGMSG command sent with a typing tag using the client-only prefix + and possible values of active, paused, and done.
>
> The typing-active notification SHOULD be sent ONCE by client when the user begins typing into text-input field and the text is not a "/slash command". After the user has begun typing if focus is lost or no further typing has occurred for 5 seconds a typing-paused notification should be sent, when typing is resumed ONE more typing-active SHOULD be sent. If a user is still typing 30 seconds after sending the last active-notification the client should send another active notification. If the user clears the text-input field without sending a message, the client SHOULD send a typing-done notification.
>
> Input event handlers SHOULD be throttled so that typing notifications are not sent within 3 seconds of each other for a given target.

> After receiving a typing notification, clients SHOULD assume the sender is still typing until either a message is received, the sender leaves the channel or quits the server, or a pause/done notification is received. If 40 seconds has elapsed since the last typing pause/active notification was received clients SHOULD assume the user is no longer typing.

**Comment by RyanSquared** [comment]
> If the user clears the text-input field without sending a message, the client SHOULD send a typing-done notification.

and

> Input event handlers SHOULD be throttled so that typing notifications are not sent within 3 seconds of each other for a given target.

seem to contradict each other. Not to mention, if a "paused" message is sent and the user immediately starts typing again - which can happen - the typing would not be sent. Overall, I think it's a bit difficult to read. I would phrase it like:

> Format
>
> A typing notification is represented by a TAGMSG command sent with a typing tag using the client-only prefix + and possible values "active", "paused", and "done".
>
> Once a user starts typing and the client knows a message will be sent to a channel (for example, with `/me` or `/msg`), the typing-active notification (a TAGMSG with the value set to "active") SHOULD be sent every 15 seconds the user continues typing. If focus is lost or no further typing has occurred for 5 seconds, a typing-paused notification (a TAGMSG with the value set to "paused") SHOULD be sent. When typing is resumed, a single typing-active message SHOULD be sent. If the user clears the text-input field without sending a message and does not resume typing for 5 seconds, a typing-done notification (a TAGMSG with the value set to "done") SHOULD be sent.

I do not agree with the typing notification limits, so I have removed that paragraph. I also do not agree with clients assuming that another client is still typing. I think that they should wait until the next typing-active message and that a typing-active message should be sent once the client begins typing again.

**Comment by jwheare** [comment]
I believe this issue was opened due to a server bug with TAGMSG that was causing extra load that has since been fixed, so it's probably not all that relevant anymore.

**Comment by RyanSquared** [comment]
Perhaps the original intent is not still relevant, but I still stand by the points that I've made. Should I open up another issue or PR for those?

**Comment by RyanSquared** [comment]
I think most of my comments were made at perhaps an unfinished copy of the spec I had locally? Most of these changes are in fact already done in the live draft spec.

**Comment by jwheare** [comment]
Always good to look over stuff again :)
