### ISSUE TITLE
address confusion around the relationship between ratified message-tags and legacy tag caps

### ISSUE THREAD

**Issue by slingamn** [ircv3/ircv3-specifications#387]
Current versions of, e.g., the [server-time](https://ircv3.net/specs/extensions/server-time-3.2.html) spec link to the [ratified message-tags spec](https://ircv3.net/specs/extensions/message-tags.html). That spec includes the following language:

>Tags are enabled via capability negotiation. Clients and servers that negotiate a capability that uses tags MUST support the full tag specification.

which was intended to apply to *future* clients and tags, not to "legacy" tags from before the ratification of the final message-tags spec.

This has led to confusion among server implementers as to whether a client who negotiates `server-time` can be sent unrelated tags, such as client-only tags, with the expectation that they will successfully parse and then ignore them. The spec should clarify that this is disallowed (and possibly make explicit that the reverse is allowed, i.e., that a client who negotiates `message-tags` can be sent `time` tags even when they didn't request them).

**Comment by RyanSquared** [comment]
A suggestion that I had was to amend the older specifications to specifically note that the only requirement for the specification is that the tag format in the IRC line must be readable, and that the capability itself and `TAGMSG` is not required to be enabled.

**Comment by jwheare** [comment]
Addressed in #389
