### ISSUE TITLE
away-notify and changing away reasons

### ISSUE THREAD

**Issue by syzop** [ircv3/ircv3-specifications#397]
The current away-notify specification does not state what happens when someone is **changing** their away reason, eg:
```AWAY :reason 1```
And then a while later:
```AWAY :reason 2```

The specification only talks about changing states, and strictly speaking changing from being away to being away is not a change of state. This is what the spec says:
> [..] clients will be sent an AWAY message when a user sharing a channel with them sets or removes their away state [..]

At UnrealIRCd, and I just checked: at ircd-seven and inspircd too, we send a new AWAY message to away-notify users with the updated reason. Rationale is that, since the reason field is sent to away-notify, it makes sense to update them to these clients. Otherwise, strictly speaking, it's a desync of the reason field: the away-notify recipients would otherwise only know the old reason, which is no longer valid and one can see how this is potentially confusing.

I think the spec should be updated on this.

**Comment by jwheare** [comment]
> [..] clients will be sent an AWAY message when a user sharing a channel with them sets or removes their away state [..]

My reading of this pretty unambiguously includes "changes" as part of "sets", but if that's not clear to everyone we can add that.
