### ISSUE TITLE
vhost emoji support feasible ?

### ISSUE THREAD

**Issue by SasaDermanovic** [ircv3/ircv3-specifications#409]
By vhost I mean the part after someones nick name, e.g sasa@**custom.vhost** .
Would it be possible that it could contain emojis and display them, eg sasa@display.emoji.🍀 for example ?

**Comment by DanielOaks** [comment]
Thanks for the issue! If a server wants to do it then they could. I don't see any doing it but it might happen. I'll close this issue but if there's a concrete feature based around this then feel free to flesh it out and file an issue against our ideas repo: https://github.com/ircv3/ircv3-ideas/ (or probably more appropriate, bring the feature up with a services package / ircd that might consider implementing the feature themselves).
