### ISSUE TITLE
Website Modernization & Reorganization

### ISSUE THREAD

**Issue by Aerdan** [ircv3/ircv3-specifications#44]
I believe that the website is presently organized suboptimally, in that most content is placed on one page. I propose, therefore, that it be migrated to Jekyll and that the following model be used for arranging documentation:

/index -- explain what IRCv3 is and what we're doing.
/$version/index -- explain, briefly, the goals of IRCv$version and enumerate the specifications therein.
/$version/$specname -- documents the relevant specification
/documentation/ -- contains all documentation relevant to IRCv3 implementations which is not itself a specification, e.g. SASL mechanisms.
/implementations -- lists all compliant implementations, probably by version.

I think Bootstrap would be a good basis for look & feel, however it shouldn't use the default colours.

**Comment by DanielOaks** [comment]
I think we can call this done

**Comment by attilamolnar** [comment]
Thanks to @DanielOaks for his effort and everyone else who helped in this.
