### ISSUE TITLE
A capability for enabling receiving arbitrary standard replies

### ISSUE THREAD

**Issue by SadieCat** [ircv3/ircv3-specifications#445]
Currently sending arbitrary standard replies to clients is problematic as not all clients can handle them properly. Some swallow the message entirely and some print them as junk to the server window. This is obviously non-ideal and it would be nice to have a standard workaround for this.

As a vendor-specific workaround InspIRCd currently ships an `inspircd.org/standard-replies` capability which allows clients to opt-in to receiving arbitrary standard replies that it might not otherwise have enabled support for. If the user has the capability enabled they get a standard reply and if they don't they just get a notice formatted like `*** COMMAND: Message goes here` instead. We plan to use this to convert the majority of our custom error numerics and server-originated error notices over to standard replies.

This would be useful with specs like #432 that don't explicitly require a client to opt-in to them but that may result in a standard reply being sent to the client.

**Comment by DanielOaks** [comment]
Could also be useful for the `ACCOUNT_REQUIRED` code that we send to clients, right now we just send that to clients unprompted. I imagine this would be used to deliver most/all server notices generally if the capability is enabled? I do really like the idea of sending server notices with `NOTE`s and such.

Originally with standard-replies, we discussed defining a few numerics (like `RPL_STDREPLYNOTE`, `ERR_STDREPLYFAIL`, etc, or just one numeric for all three types) and sending the standard replies as those unless the user requested a specific cap, but I thiiink we threw that out as being a bit too complicated to be worth it? I wouldn't be opposed to doing this, but would like to hear thoughts from other implementors before jumping on board.

**Comment by slingamn** [comment]
What are the numerics that would be replaced by standard replies under this proposal?

**Comment by SadieCat** [comment]
We have a lot of custom numerics in InspIRCd that are exclusively used by InspIRCd modules and that aren't really supported by clients (e.g. ERR_AMBIGUOUSCOMMAND). I'm not proposing we replace any standard/common numerics with standard replies right as part of this proposal.
