### ISSUE TITLE
sasl spec should clarify that AUTHENTICATE is a normal IRC message

### ISSUE THREAD

**Issue by slingamn** [ircv3/ircv3-specifications#467]
The [SASL 3.1 spec](https://ircv3.net/specs/extensions/sasl-3.1) makes it sound as though AUTHENTICATE is its own subprotocol with its own grammar. This is a persistent source of confusion because implementations fail to handle AUTHENTICATE with prefixes or tags. Some examples:

1. [ZNC](https://github.com/znc/znc/issues/1212)
2. [Pidgin/libpurple](https://keep.imfreedom.org/pidgin/pidgin/rev/86e7c9ca0bcd)
3. [Weechat](https://github.com/weechat/weechat/issues/1679)

The spec should be amended to make it clear that `AUTHENTICATE` is a normal IRC message.

**Comment by ailin-nemui** [comment]
4. https://github.com/pircbotx/pircbotx/issues/401

**Comment by ailin-nemui** [comment]
points:
* `:+` and `:*` are all valid and need to be parsed
* optional `:server.` can be given
* message tags, when enabled
