### ISSUE TITLE
Labeled replies

### ISSUE THREAD

**Issue by DarthGandalf** [ircv3/ircv3-specifications#53]
Client attaches a cookie to the request and get that same cookie back in the response message(s).
Useful for ZNC, when multiple clients are connected, instead of hacky http://wiki.znc.in/Route_replies

See #51

**Comment by xPaw** [comment]
This is indeed a good idea! Just now I was thinking on how to catch replies to my bot's commands, but came to a conclusion that there is no reliable way of getting initial command which caused said reply to happen, attaching a cookie to commands would solve this problem.

**Comment by jwheare** [comment]
Discussion is moved to #162
