### ISSUE TITLE
irc Some privacy issues

### ISSUE THREAD

**Issue by Pantyhose-X** [ircv3/ircv3-specifications#533]
* irc logs ip. 
> Anyone can see it. It's dangerous.  For example, you're located in Russia and you're talking about the war in Ukraine and you're waiting to be arrested.  Any company will sell your data if there's enough profit in it! Just because it's not public doesn't mean it's not there.

* No PIN
> There's no PIN code on the room. Anyone can break in.

* Not support Image
> A single image can save a lot of text.

**Comment by DarthGandalf** [comment]
> irc logs ip.

Some servers has a concept of cloak, which is set either automatically or by request; which hides the IP. Or you can always use an IRC bouncer, or a VPN, then even IRC server itself won't see your IP.

> No PIN

It's called [channel mode +k](https://www.rfc-editor.org/rfc/rfc1459#section-4.2.3.1). And unlike "PIN", it's not limited to digits.

> A single image can save a lot of text.

Do you mean instagram-style image which is actually lots of text, or what?

If you mean posting an image, so far usually it's been done in IRC by hosting the image elsewhere and posting an URL to it. Some clients then show a preview of the image.

**Comment by Pantyhose-X** [comment]
> cloak
cloak should be enabled by default. They need to authenticate your mail to enable cloak.
They block Tor VPN.
irc has no advantage over xmpp.

**Comment by classabbyamp** [comment]
who is 'they'? IRC is a collection of many networks with different policies, capabilities, and implementations

**Comment by DarthGandalf** [comment]
Some IRC networks offer Tor service.

If you don't like the policy of some particular network, choose another one. You can even setup your own and do with it whatever you want.

**Comment by acidvegas** [comment]
lol....
