### ISSUE TITLE
Roaming clients

### ISSUE THREAD

**Issue by attilamolnar** [ircv3/ircv3-specifications#76]
Allow clients to roam to another server and retain their complete state in case their server has to be shut down or rebooted (due to system upgrades, etc.).

**Comment by h1z1** [comment]
Why would this need to be part of a spec when proxies already accomplish it?

IRC is ephemeral for a reason, that isn't a bug it's a feature.

**Comment by jwheare** [comment]
This is too old to be a useful issue anyway. Closing to prevent further necroposts.
