### ISSUE TITLE
Let servers advertise to clients that they are secure-preferred

### ISSUE THREAD

**Issue by attilamolnar** [ircv3/ircv3-specifications#77]
Raised by @jwheare

**Comment by voltagex** [comment]
@wilhelmy I agree, how about secure-by-default?

**Comment by attilamolnar** [comment]
"Secure by default" is a good sounding phrase but conveys none of the actions to take to achieve security. STS with preload lists are one step in that direction, it provides a working upgrade path. The next step could be restricting new features to secure connections for example. Doing only the latter requires users to reconfigure all servers they use manually instead of the client doing it.

**Comment by synandro** [comment]
Maybe extend RPL_REDIR(010 numeric) a little to support saying to clients to direct to server/port and somehow say that it's an SSL port.  

*** RPL_REDIR ***/             ":%s %d :Please use this SSL Server/Port instead" perhaps?

Or simply just don't listen on a plaintext port.  Not everything needs to be over-engineered ;)

**Comment by attilamolnar** [comment]
The specification covering the basics has been merged. I have opened new issues for the next TODO items.
