### ISSUE TITLE
Import WHOX spec

### ISSUE THREAD

**Issue by jwheare** [ircv3/ircv3-specifications#81]
Note that some implementations in the wild have vendor specific variations. E.g. rules on case sensitivity, the `H` (real host names) option, join-delayed channel members.

It would be useful to document the base compatibility case for new implementations and highlight any areas where vendor-extensions are possible.

https://github.com/quakenet/snircd/blob/master/doc/readme.who
http://faerion.sourceforge.net/doc/irc/whox.var

**Comment by slingamn** [comment]
@ilbelkyr expressed interest in this :1st_place_medal:

**Comment by SadieCat** [comment]
It might be a neat WHOX extension to add a value to the ISUPPORT token like `WHOX=[flags],[fields]` so that if server vendor has custom fields/flags they can let clients know about them

We do something similar to this with ESILENCE in InspIRCd for our SILENCE flags.

(cc @ilbelkyr)

**Comment by emersion** [comment]
I'm in the process of documenting WHO on modern.ircdocs.horse (https://github.com/ircdocs/modern-irc/pull/138), and I'm wondering: would WHOX make more sense as a modern.ircdocs.horse patch or as an IRCv3 ext? cc @progval

**Comment by jwheare** [comment]
I think it'd help to have it in IRCv3 given its long standing non-standardisation. But no reason it can't be on modern too.

**Comment by emersion** [comment]
Opened https://github.com/ircv3/ircv3-specifications/pull/482
