### ISSUE TITLE
Add message tag that indicates a playback message

### ISSUE THREAD

**Issue by jaingaurav** [ircv3/ircv3-specifications#85]
Currently playback messages are treated as regular messages by bouncers and provide no indication to a client that they are replay messages. Certain clients such as Textual assume that replay messages is one with the server-time tag added. This is the current behavior of znc. There is no reason that a server cannot add a server-time tag to all messages, thus I propose that a new tag be added that indicates a playback message to clients.

Clients may like to specially handle playback messages. For example, Textual has an option to not post notifications for playback messages. There are other use cases such as handling joins and parts. If a client knows that the message is part of the playback it need not update it channel state. This issue was discussed in #znc where in order to support joins and parts in the playback buffer, either the znc bouncer would have to maintain an 'old state' which is from the start of the playback buffer or clients could simply print joins and parts from the playback buffer.

A new CAP would be needed to support this feature thereby enabling a bouncer to freely send joint, parts, etc. The responsibility of the client would be to understand messages with this tag do not reflect the current state of a channel and as such should not be acted upon.

**Comment by attilamolnar** [comment]
The chathistory batch type which was added recently by @SaberUK covers this entirely.
